"""
Phase-Map Store — in-memory state for the EDS phase-map builder.

Also owns the deterministic phase-colour palette (one fixed RGB tuple
per phase index) so the legend, the rendered preview, and any future
overlay all show the same colour for the same phase. The palette is
generated by golden-ratio rotation in HSV space, which gives
well-spaced colours regardless of how many CIFs the user has.

Holds the result of an auto-classification (per-pixel CIF assignment)
and any subsequent manual edits, so:

- M3 visualises the phase map without re-classifying on every redraw
- M4 lets the user paint a region with a different phase id
- M5 hands per-phase pixel masks to the indexing pipeline

Lifecycle is **per backend process**: cleared on file open/close so
stale phase maps from a previous EBSD file can never leak into the
next session.

Persistence: every successful ``set_classification`` and
``assign_region`` call also writes a sidecar ``.phase_map.npz`` next
to the EBSD file. On the next ``open_file()`` for that path, the
sidecar is auto-reloaded so the user does not have to re-run
auto-classify after restarting the backend (or come back to a 30 min
classification result that was just kicked out of memory).
"""
from __future__ import annotations

import json
import logging
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

from backend.api.services.cif_phase_library import CifPhaseEntry


# Single-source schema version so older sidecars (or sidecars from a
# fork) get rejected cleanly instead of crashing the load. Bump only
# on incompatible changes — adding optional fields is fine.
_SIDECAR_SCHEMA = 1


def _sidecar_path_for(file_path: str) -> Path:
    """Return ``<file_path>.phase_map.npz`` — the canonical sidecar name.

    Sticking the suffix on the *full* filename (rather than swapping
    the original suffix) means ``foo.h5oina`` becomes
    ``foo.h5oina.phase_map.npz``, not ``foo.phase_map.npz``. That keeps
    multi-suffix files distinguishable and side-steps Path.with_suffix
    eating the leading ``.h5oina``.
    """
    p = Path(file_path)
    return p.with_name(p.name + ".phase_map.npz")

logger = logging.getLogger(__name__)


@dataclass
class PhaseMapState:
    """One full phase classification for the currently loaded EBSD file.

    Pixel ids in ``phase_grid`` are indices into ``phase_entries`` (or
    ``-1`` for unclassified). Keeping the entry list rather than a
    dict makes the rendering side trivial — the entry index is also
    the colour-table index.
    """

    phase_grid: np.ndarray            # int32 (n_rows, n_cols), -1 = unclassified
    score_grid: np.ndarray            # float32 (n_rows, n_cols), 0..1
    phase_entries: List[CifPhaseEntry]
    n_rows: int
    n_cols: int
    tolerance: float
    min_score: float
    # Locked grids: pixels the user has manually overwritten so the
    # next auto-classify round does not silently revert them. None
    # until the first manual edit (saves a 2D bool allocation when
    # nobody touches the map).
    locked_mask: Optional[np.ndarray] = field(default=None)


class PhaseMapStore:
    """Process-wide store for one phase map at a time.

    Thread-safe because the backend route handlers can be invoked
    concurrently (uvicorn workers + auto-classify is not awaitable).
    Only one phase map is held — switching EBSD files clears it. The
    indexing pipeline reads it via :meth:`get_phase_masks` to drive
    multi-phase per-region runs.
    """

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._state: Optional[PhaseMapState] = None
        self._file_path: Optional[str] = None  # tag so we can detect file switches

    # --- Lifecycle ---

    def clear(self) -> None:
        with self._lock:
            self._state = None
            self._file_path = None

    def is_set(self) -> bool:
        with self._lock:
            return self._state is not None

    def file_path(self) -> Optional[str]:
        with self._lock:
            return self._file_path

    # --- Set / get full state ---

    def set_classification(
        self,
        phase_grid: np.ndarray,
        score_grid: np.ndarray,
        phase_entries: List[CifPhaseEntry],
        tolerance: float,
        min_score: float,
        file_path: Optional[str] = None,
    ) -> None:
        """Replace the stored classification with a freshly computed one.

        Auto-saves a sidecar when ``file_path`` is known, so a backend
        restart doesn't lose the classification.
        """
        with self._lock:
            n_rows, n_cols = phase_grid.shape
            self._state = PhaseMapState(
                phase_grid=phase_grid.astype(np.int32, copy=True),
                score_grid=score_grid.astype(np.float32, copy=True),
                phase_entries=list(phase_entries),
                n_rows=int(n_rows),
                n_cols=int(n_cols),
                tolerance=float(tolerance),
                min_score=float(min_score),
                locked_mask=None,
            )
            self._file_path = file_path
        self._autosave()

    def get_state(self) -> Optional[PhaseMapState]:
        with self._lock:
            return self._state

    # --- Editing (M4) ---

    def assign_region(
        self,
        row_start: int,
        row_end: int,
        col_start: int,
        col_end: int,
        target_phase_index: int,
    ) -> int:
        """Paint a rectangular region with a phase id.

        ``target_phase_index = -1`` means "mark these pixels as
        unclassified". Otherwise the index must be valid in the
        current ``phase_entries`` list — we refuse out-of-range writes
        rather than silently corrupting the grid (fail-loud).

        Returns the number of pixels actually overwritten.
        """
        with self._lock:
            if self._state is None:
                raise RuntimeError("No phase map loaded — run auto-classify first")
            st = self._state
            if target_phase_index != -1 and not (0 <= target_phase_index < len(st.phase_entries)):
                raise ValueError(
                    f"Phase index {target_phase_index} out of range "
                    f"(0..{len(st.phase_entries) - 1})"
                )

            r0 = max(0, int(row_start))
            r1 = min(st.n_rows - 1, int(row_end))
            c0 = max(0, int(col_start))
            c1 = min(st.n_cols - 1, int(col_end))
            if r0 > r1 or c0 > c1:
                return 0

            sub = st.phase_grid[r0:r1 + 1, c0:c1 + 1]
            n = int(sub.size)
            sub[:] = int(target_phase_index)

            # Track manually-overwritten pixels so a "re-classify in
            # region" or full re-classify call can preserve them on
            # request later. Lazy-allocate to keep memory low for
            # users who never paint.
            if st.locked_mask is None:
                st.locked_mask = np.zeros((st.n_rows, st.n_cols), dtype=bool)
            st.locked_mask[r0:r1 + 1, c0:c1 + 1] = True

            # Score is meaningless after manual override — set to 1.0
            # for assigned pixels and 0.0 for cleared pixels so
            # downstream consumers can still threshold sensibly.
            score_sub = st.score_grid[r0:r1 + 1, c0:c1 + 1]
            score_sub[:] = 1.0 if target_phase_index != -1 else 0.0
        self._autosave()
        return n

    def assign_mask(
        self,
        mask: np.ndarray,
        target_phase_index: int,
    ) -> int:
        """Paint an arbitrary 2D bool mask with a phase id.

        Generalised counterpart to :meth:`assign_region` — used by
        polygon / brush / lasso paint where the affected pixels don't
        form a rectangle. Same fail-loud rules: out-of-range phase
        index raises, no in-memory state is loaded raises, mismatched
        shape raises.

        Returns the number of pixels actually overwritten.
        """
        with self._lock:
            if self._state is None:
                raise RuntimeError("No phase map loaded — run auto-classify first")
            st = self._state
            if mask.shape != (st.n_rows, st.n_cols):
                raise ValueError(
                    f"mask shape {mask.shape} does not match phase grid "
                    f"shape {(st.n_rows, st.n_cols)}"
                )
            if target_phase_index != -1 and not (0 <= target_phase_index < len(st.phase_entries)):
                raise ValueError(
                    f"Phase index {target_phase_index} out of range "
                    f"(0..{len(st.phase_entries) - 1})"
                )
            bool_mask = mask.astype(bool, copy=False)
            n = int(bool_mask.sum())
            if n == 0:
                return 0
            st.phase_grid[bool_mask] = int(target_phase_index)
            if st.locked_mask is None:
                st.locked_mask = np.zeros((st.n_rows, st.n_cols), dtype=bool)
            st.locked_mask[bool_mask] = True
            st.score_grid[bool_mask] = 1.0 if target_phase_index != -1 else 0.0
        self._autosave()
        return n

    # --- Persistence ---

    def _autosave(self) -> None:
        """Best-effort sidecar write — never raises into callers.

        A failed save is never worth aborting the in-memory set —
        the user's edit is still applied, they just won't have it
        across a backend restart. The exception is logged so a
        consistent failure (read-only filesystem, etc.) is at least
        diagnosable.
        """
        with self._lock:
            if self._state is None or not self._file_path:
                return
            file_path = self._file_path
        try:
            self.save_to_disk(file_path)
        except Exception:
            logger.exception("Phase-map sidecar autosave failed for %s", file_path)

    def save_to_disk(self, file_path: str) -> Optional[Path]:
        """Write the current state to ``<file_path>.phase_map.npz``.

        Returns the sidecar path on success, ``None`` if there is no
        state to save (the public API; ``_autosave`` already handled
        the silent path).

        Format: a single ``.npz`` with the int-grid + float-grid + an
        embedded JSON blob for the per-phase metadata. JSON keeps the
        loader free of pickle (which we'd otherwise need for the
        dataclass list and which has security implications when the
        sidecar comes from a shared location).
        """
        with self._lock:
            state = self._state
            if state is None:
                return None
            entries_payload = [
                {
                    "key": e.key,
                    "cif_filename": e.cif_filename,
                    "formula": e.formula,
                    "space_group": e.space_group,
                    "space_group_number": e.space_group_number,
                    "crystal_system": e.crystal_system,
                    "composition": dict(e.composition),
                    "elements": list(e.elements),
                }
                for e in state.phase_entries
            ]
            payload = {
                "schema": _SIDECAR_SCHEMA,
                "n_rows": state.n_rows,
                "n_cols": state.n_cols,
                "tolerance": state.tolerance,
                "min_score": state.min_score,
                "entries": entries_payload,
            }
            sidecar = _sidecar_path_for(file_path)
            np.savez_compressed(
                str(sidecar),
                phase_grid=state.phase_grid,
                score_grid=state.score_grid,
                # Optional locked_mask: store as empty array when unset
                # so the loader can detect "no manual edits" cheaply.
                locked_mask=(state.locked_mask if state.locked_mask is not None
                             else np.zeros((0, 0), dtype=bool)),
                meta=np.array(json.dumps(payload), dtype=str),
            )
        return sidecar

    def load_from_disk(self, file_path: str) -> bool:
        """Restore state from a sidecar if one exists. Returns True on hit.

        Schema mismatch / corrupt file / missing file all return False
        without touching the current state — callers (e.g. open_file)
        treat False as "nothing to restore" and continue normally.
        """
        sidecar = _sidecar_path_for(file_path)
        if not sidecar.is_file():
            return False
        try:
            with np.load(str(sidecar), allow_pickle=False) as data:
                meta_raw = data["meta"]
                # ``np.array(json_str, dtype=str)`` produces a 0-d
                # array; ``.item()`` unwraps it back to a Python str.
                meta = json.loads(meta_raw.item() if meta_raw.ndim == 0 else str(meta_raw))
                if meta.get("schema") != _SIDECAR_SCHEMA:
                    logger.info(
                        "Phase-map sidecar %s has schema %s, expected %s — ignoring.",
                        sidecar, meta.get("schema"), _SIDECAR_SCHEMA,
                    )
                    return False
                phase_grid = data["phase_grid"]
                score_grid = data["score_grid"]
                locked_arr = data["locked_mask"]
        except Exception:
            logger.exception("Failed to load phase-map sidecar %s", sidecar)
            return False

        try:
            entries = [
                CifPhaseEntry(
                    key=e["key"],
                    cif_filename=e["cif_filename"],
                    formula=e.get("formula", ""),
                    space_group=e.get("space_group", ""),
                    space_group_number=e.get("space_group_number"),
                    crystal_system=e.get("crystal_system", ""),
                    composition=dict(e["composition"]),
                    elements=list(e["elements"]),
                )
                for e in meta["entries"]
            ]
        except KeyError:
            logger.exception(
                "Phase-map sidecar %s entries are malformed — ignoring.", sidecar
            )
            return False

        n_rows = int(meta["n_rows"])
        n_cols = int(meta["n_cols"])
        if phase_grid.shape != (n_rows, n_cols):
            logger.warning(
                "Phase-map sidecar %s: phase_grid shape %s != meta shape %s — ignoring.",
                sidecar, phase_grid.shape, (n_rows, n_cols),
            )
            return False

        locked = locked_arr if locked_arr.size > 0 else None
        with self._lock:
            self._state = PhaseMapState(
                phase_grid=phase_grid.astype(np.int32, copy=True),
                score_grid=score_grid.astype(np.float32, copy=True),
                phase_entries=entries,
                n_rows=n_rows,
                n_cols=n_cols,
                tolerance=float(meta.get("tolerance", 15.0)),
                min_score=float(meta.get("min_score", 0.3)),
                locked_mask=locked.astype(bool, copy=True) if locked is not None else None,
            )
            self._file_path = file_path
        logger.info("Phase-map sidecar restored from %s (%d phases, %dx%d)",
                    sidecar, len(entries), n_rows, n_cols)
        return True

    # --- Read API for indexing (M5) and visualisation (M3) ---

    def phase_summary(self) -> List[Dict]:
        """Per-phase counts + percentage for the legend / phase list UI."""
        with self._lock:
            if self._state is None:
                return []
            st = self._state
            total = st.n_rows * st.n_cols
            # Bincount over a positive-shifted grid so -1 lands at index 0.
            shifted = (st.phase_grid + 1).ravel()
            counts = np.bincount(shifted, minlength=len(st.phase_entries) + 1)
            unclassified = int(counts[0])
            summary: List[Dict] = []
            for i, entry in enumerate(st.phase_entries):
                n = int(counts[i + 1])
                if n == 0:
                    continue  # skip phases with no pixels (not needed in the legend)
                summary.append({
                    "phase_index": i,
                    "cif_filename": entry.cif_filename,
                    "formula": entry.formula,
                    "space_group": entry.space_group,
                    "space_group_number": entry.space_group_number,
                    "crystal_system": entry.crystal_system,
                    "elements": list(entry.elements),
                    "n_pixels": n,
                    "percentage": round(n / total * 100, 2) if total > 0 else 0.0,
                })
            summary.append({
                "phase_index": -1,
                "cif_filename": "",
                "formula": "",
                "space_group": "",
                "crystal_system": "",
                "n_pixels": unclassified,
                "percentage": round(unclassified / total * 100, 2) if total > 0 else 0.0,
                "is_unclassified": True,
            })
            return summary

    def get_phase_masks(self) -> Tuple[List[CifPhaseEntry], Dict[int, np.ndarray]]:
        """Return ``({phase_index: bool_mask_2d}, ordered_phase_entries)``.

        Used by the indexing pipeline (M5) to drive a per-phase run:
        for each entry that has a non-empty mask, run indexing only on
        those pixels with that phase as the candidate. Unclassified
        pixels are excluded entirely — those need to be either
        manually assigned or left uniform-tested in a separate pass.
        """
        with self._lock:
            if self._state is None:
                return [], {}
            st = self._state
            masks: Dict[int, np.ndarray] = {}
            for i in range(len(st.phase_entries)):
                m = st.phase_grid == i
                if m.any():
                    masks[i] = m
            return list(st.phase_entries), masks


def phase_palette(n: int) -> List[Tuple[int, int, int]]:
    """Return ``n`` visually distinct RGB colours, deterministic.

    Uses golden-ratio rotation in HSV space so any prefix of the
    sequence remains well-distributed — adding a phase doesn't
    re-shuffle the colours for the existing ones.
    """
    import colorsys
    golden = 0.618033988749895
    colours: List[Tuple[int, int, int]] = []
    h = 0.13  # offset away from pure red
    for i in range(n):
        h = (h + golden) % 1.0
        s = 0.65 if i % 2 else 0.85
        v = 0.85 if i % 2 else 0.95
        r, g, b = colorsys.hsv_to_rgb(h, s, v)
        colours.append((int(r * 255), int(g * 255), int(b * 255)))
    return colours


def render_phase_map_to_base64(state: PhaseMapState) -> str:
    """Encode the phase grid as a PNG with one fixed colour per phase.

    Unclassified pixels (-1) are rendered as a dark grey so the
    visualisation never confuses "we tested this pixel and gave up"
    with "we coloured it the same as some real phase". Returns the
    raw base64 string (no ``data:`` prefix) — same format every other
    image-returning endpoint already uses.
    """
    import base64
    import io
    from PIL import Image  # already a project dep via image_utils

    palette = phase_palette(len(state.phase_entries))
    rgb = np.zeros((state.n_rows, state.n_cols, 3), dtype=np.uint8)
    rgb[...] = (60, 60, 60)  # unclassified

    for i, colour in enumerate(palette):
        mask = state.phase_grid == i
        if not mask.any():
            continue
        rgb[mask] = colour

    # mode= is deprecated in Pillow 13; the array shape (H, W, 3) is
    # already unambiguous, so omitting the mode is the right call.
    img = Image.fromarray(rgb)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode("ascii")


def palette_hex_for_state(state: PhaseMapState) -> List[str]:
    """Hex strings for the legend — one per ``phase_entries`` slot."""
    return [f"#{r:02x}{g:02x}{b:02x}" for (r, g, b) in phase_palette(len(state.phase_entries))]


# Singleton — one phase map per backend process is enough for now.
# If we ever want N concurrent files in one backend we can promote
# this to a ``Dict[file_path, PhaseMapStore]``, but every other piece
# of the EDS stack is already single-file (extractor, calibration
# store) so matching that keeps things consistent.
_STORE = PhaseMapStore()


def get_phase_map_store() -> PhaseMapStore:
    return _STORE
