"""
Phase-Map Store — in-memory state for the EDS phase-map builder.

Also owns the deterministic phase-colour palette (one fixed RGB tuple
per phase index) so the legend, the rendered preview, and any future
overlay all show the same colour for the same phase. The palette is
generated by golden-ratio rotation in HSV space, which gives
well-spaced colours regardless of how many CIFs the user has.

Holds the result of an auto-classification (per-pixel CIF assignment)
and any subsequent manual edits, so:

- M3 visualises the phase map without re-classifying on every redraw
- M4 lets the user paint a region with a different phase id
- M5 hands per-phase pixel masks to the indexing pipeline

Lifecycle is **per backend process**: cleared on file open/close so
stale phase maps from a previous EBSD file can never leak into the
next session.

Persistence: every successful ``set_classification`` and
``assign_region`` call also writes a sidecar ``.phase_map.npz`` next
to the EBSD file. On the next ``open_file()`` for that path, the
sidecar is auto-reloaded so the user does not have to re-run
auto-classify after restarting the backend (or come back to a 30 min
classification result that was just kicked out of memory).
"""
from __future__ import annotations

import json
import logging
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
from scipy import ndimage

from backend.api.services.cif_phase_library import CifPhaseEntry


# Single-source schema version so older sidecars (or sidecars from a
# fork) get rejected cleanly instead of crashing the load. Bump only
# on incompatible changes — adding optional fields is fine.
# 2 (2026-08-19): the classifier's scoring rule changed from mean At.%
# deviation to renormalised L1 with a relative missing-major veto.
# 3 (2026-08-20): the relative veto was replaced by ratio matching plus an
# enrichment gate measured against each map's own background. A sidecar
# written by an older rule would silently outlive the rule that produced
# it, so those files are ignored and the map is recomputed.
_SIDECAR_SCHEMA = 4


def _sidecar_path_for(file_path: str) -> Path:
    """Return ``<file_path>.phase_map.npz`` — the canonical sidecar name.

    Sticking the suffix on the *full* filename (rather than swapping
    the original suffix) means ``foo.h5oina`` becomes
    ``foo.h5oina.phase_map.npz``, not ``foo.phase_map.npz``. That keeps
    multi-suffix files distinguishable and side-steps Path.with_suffix
    eating the leading ``.h5oina``.
    """
    p = Path(file_path)
    return p.with_name(p.name + ".phase_map.npz")

logger = logging.getLogger(__name__)


@dataclass
class PhaseMapState:
    """One full phase classification for the currently loaded EBSD file.

    Pixel ids in ``phase_grid`` are indices into ``phase_entries`` (or
    ``-1`` for unclassified). Keeping the entry list rather than a
    dict makes the rendering side trivial — the entry index is also
    the colour-table index.
    """

    phase_grid: np.ndarray            # int32 (n_rows, n_cols), -1 = unclassified
    score_grid: np.ndarray            # float32 (n_rows, n_cols), 0..1
    phase_entries: List[CifPhaseEntry]
    n_rows: int
    n_cols: int
    tolerance: float
    min_score: float
    # Locked grids: pixels the user has manually overwritten so the
    # next auto-classify round does not silently revert them. None
    # until the first manual edit (saves a 2D bool allocation when
    # nobody touches the map).
    locked_mask: Optional[np.ndarray] = field(default=None)
    # --- Structures (2026-08-24) ---
    # A structure is a group of pixels that belong together by composition
    # alone, before anything is named. ``phase_grid`` stays authoritative —
    # it has five consumers outside this module — and a structure assignment
    # simply writes into it through the same path as any hand edit. That also
    # keeps hand edits possible on pixel sets that respect no structure
    # boundary at all (wand, rectangle, polygon).
    structure_grid: Optional[np.ndarray] = field(default=None)   # int32, -1 = none
    # structure id -> index into ``phase_entries``, or -1 for "not named yet".
    structure_phase: List[int] = field(default_factory=list)

    @property
    def n_structures(self) -> int:
        return len(self.structure_phase)


class PhaseMapStore:
    """Process-wide store for one phase map at a time.

    Thread-safe because the backend route handlers can be invoked
    concurrently (uvicorn workers + auto-classify is not awaitable).
    Only one phase map is held — switching EBSD files clears it. The
    indexing pipeline reads it via :meth:`get_phase_masks` to drive
    multi-phase per-region runs.
    """

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._state: Optional[PhaseMapState] = None
        self._file_path: Optional[str] = None  # tag so we can detect file switches
        # The composition the structures were clustered on, as the same
        # feature matrix the clustering used (n_px x n_elements). Splitting a
        # structure needs it; nothing else does, so it is held beside the
        # state rather than inside it — it is derived data, it must not go in
        # the sidecar, and it must not be restored by undo.
        self._structure_features: Optional[np.ndarray] = None
        # One-level undo. Every mutation snapshots the whole state first, so
        # undo restores phase ids, scores, the locked mask AND the candidate
        # list together — restoring the grid alone would leave phase ids
        # pointing into a different list, which is the same class of bug the
        # locked-mask carry-over had to avoid. Deliberately one level: a deep
        # history on a 485 k-px map costs real memory, and the operations
        # this guards are single deliberate acts, not typing.
        self._undo: Optional[PhaseMapState] = None
        self._undo_label: Optional[str] = None

    def _snapshot(self, label: str) -> None:
        """Remember the current state so :meth:`undo` can put it back.

        Caller must already hold the lock.
        """
        st = self._state
        if st is None:
            self._undo = None
            self._undo_label = None
            return
        self._undo = PhaseMapState(
            phase_grid=st.phase_grid.copy(),
            score_grid=st.score_grid.copy(),
            phase_entries=list(st.phase_entries),
            n_rows=st.n_rows,
            n_cols=st.n_cols,
            tolerance=st.tolerance,
            min_score=st.min_score,
            locked_mask=(st.locked_mask.copy()
                         if st.locked_mask is not None else None),
            structure_grid=(st.structure_grid.copy()
                            if st.structure_grid is not None else None),
            structure_phase=list(st.structure_phase),
        )
        self._undo_label = label

    @property
    def undo_label(self) -> Optional[str]:
        """What :meth:`undo` would take back, for the button's label."""
        with self._lock:
            return self._undo_label if self._undo is not None else None

    def undo(self) -> bool:
        """Restore the state from before the last mutation. One level.

        Returns False when there is nothing to undo, so the route can say so
        rather than pretending it did something.
        """
        with self._lock:
            if self._undo is None:
                return False
            # Swap rather than drop: undo of an undo is a redo, which is what
            # a user expects from a single-level control after a misclick.
            current, self._state = self._state, self._undo
            self._undo = current
            # Undoing an undo is a redo — what a user expects from a single
            # control after a misclick.
            self._undo_label = "redo" if self._undo_label != "redo" else "undo"
        self._autosave()
        return True

    # --- Lifecycle ---

    def clear(self) -> None:
        with self._lock:
            self._state = None
            # Drop the undo slot with it: clearing means starting over,
            # and an undo afterwards would restore a map belonging to a
            # file that is no longer the active one.
            self._undo = None
            self._undo_label = None
            self._file_path = None
            self._structure_features = None

    def is_set(self) -> bool:
        with self._lock:
            return self._state is not None

    def file_path(self) -> Optional[str]:
        with self._lock:
            return self._file_path

    # --- Set / get full state ---

    def set_classification(
        self,
        phase_grid: np.ndarray,
        score_grid: np.ndarray,
        phase_entries: List[CifPhaseEntry],
        tolerance: float,
        min_score: float,
        file_path: Optional[str] = None,
        preserve_locked: bool = True,
        structure_grid: Optional[np.ndarray] = None,
        structure_phase: Optional[List[int]] = None,
        structure_features: Optional[np.ndarray] = None,
    ) -> None:
        """Replace the stored classification with a freshly computed one.

        ``preserve_locked`` carries the user's hand-assigned pixels across
        the re-classify. ``locked_mask`` has been written on every manual
        edit since M4 and read by NOTHING: this method used to hardcode
        ``locked_mask=None``, so every re-classify silently destroyed the
        corrections the mask exists to protect. The docstring on the field
        says it is there "so the next auto-classify round does not silently
        revert them" — that consumer is this.

        Preserving requires the phase INDICES to still mean the same thing.
        They are positions in ``phase_entries``, so a run over a different
        candidate list re-numbers them; the pixels are therefore carried by
        their entry KEY, not by their index, and a locked pixel whose phase
        is no longer a candidate is dropped rather than silently repointed
        at whatever now sits at that index.

        Pass ``preserve_locked=False`` for a deliberate "start over".

        Auto-saves a sidecar when ``file_path`` is known, so a backend
        restart doesn't lose the classification.
        """
        with self._lock:
            self._snapshot("re-classify")
            n_rows, n_cols = phase_grid.shape
            new_grid = phase_grid.astype(np.int32, copy=True)
            new_scores = score_grid.astype(np.float32, copy=True)
            carried_mask = None

            prev = self._state
            if (preserve_locked and prev is not None
                    and prev.locked_mask is not None
                    and prev.locked_mask.shape == new_grid.shape):
                key_to_new = {e.key: i for i, e in enumerate(phase_entries)}
                carried_mask = np.zeros_like(prev.locked_mask)
                rows, cols = np.nonzero(prev.locked_mask)
                for r, c in zip(rows.tolist(), cols.tolist()):
                    old_idx = int(prev.phase_grid[r, c])
                    if old_idx < 0:
                        # Hand-marked as unclassified — that is a decision too.
                        new_grid[r, c] = -1
                        carried_mask[r, c] = True
                        continue
                    if old_idx >= len(prev.phase_entries):
                        continue
                    new_idx = key_to_new.get(prev.phase_entries[old_idx].key)
                    if new_idx is None:
                        # The phase left the candidate list; keeping the old
                        # index would point at an unrelated phase.
                        continue
                    new_grid[r, c] = new_idx
                    new_scores[r, c] = float(prev.score_grid[r, c])
                    carried_mask[r, c] = True
                if not carried_mask.any():
                    carried_mask = None

            self._state = PhaseMapState(
                phase_grid=new_grid,
                score_grid=new_scores,
                phase_entries=list(phase_entries),
                n_rows=int(n_rows),
                n_cols=int(n_cols),
                tolerance=float(tolerance),
                min_score=float(min_score),
                locked_mask=carried_mask,
                structure_grid=(structure_grid.astype(np.int32, copy=True)
                                if structure_grid is not None else None),
                structure_phase=(list(structure_phase)
                                 if structure_phase is not None else []),
            )
            self._structure_features = (
                np.asarray(structure_features, dtype=np.float64)
                if structure_features is not None else None
            )
            self._file_path = file_path
        self._autosave()

    def get_state(self) -> Optional[PhaseMapState]:
        with self._lock:
            return self._state

    # --- Editing (M4) ---

    def assign_region(
        self,
        row_start: int,
        row_end: int,
        col_start: int,
        col_end: int,
        target_phase_index: int,
    ) -> int:
        """Paint a rectangular region with a phase id.

        ``target_phase_index = -1`` means "mark these pixels as
        unclassified". Otherwise the index must be valid in the
        current ``phase_entries`` list — we refuse out-of-range writes
        rather than silently corrupting the grid (fail-loud).

        Returns the number of pixels actually overwritten.
        """
        with self._lock:
            if self._state is None:
                raise RuntimeError("No phase map loaded — run auto-classify first")
            st = self._state
            if target_phase_index != -1 and not (0 <= target_phase_index < len(st.phase_entries)):
                raise ValueError(
                    f"Phase index {target_phase_index} out of range "
                    f"(0..{len(st.phase_entries) - 1})"
                )

            r0 = max(0, int(row_start))
            r1 = min(st.n_rows - 1, int(row_end))
            c0 = max(0, int(col_start))
            c1 = min(st.n_cols - 1, int(col_end))
            if r0 > r1 or c0 > c1:
                return 0
            self._snapshot("assign region")

            sub = st.phase_grid[r0:r1 + 1, c0:c1 + 1]
            n = int(sub.size)
            sub[:] = int(target_phase_index)

            # Track manually-overwritten pixels so a "re-classify in
            # region" or full re-classify call can preserve them on
            # request later. Lazy-allocate to keep memory low for
            # users who never paint.
            if st.locked_mask is None:
                st.locked_mask = np.zeros((st.n_rows, st.n_cols), dtype=bool)
            st.locked_mask[r0:r1 + 1, c0:c1 + 1] = True

            # Score is meaningless after manual override — set to 1.0
            # for assigned pixels and 0.0 for cleared pixels so
            # downstream consumers can still threshold sensibly.
            score_sub = st.score_grid[r0:r1 + 1, c0:c1 + 1]
            score_sub[:] = 1.0 if target_phase_index != -1 else 0.0
        self._autosave()
        return n

    def replace_phase(self, from_phase_index: int, to_phase_index: int) -> int:
        """Repoint every pixel of one phase at another, map-wide.

        The correction a wand cannot make. The recorded case is "sd_0302719
        won 55 % of my map and it should be Al": lassoing 55 % of a map by
        hand is not a workflow, and the wand is a feature-scale instrument.

        Both ids may be -1 (unclassified), so this also serves "everything
        the classifier gave up on is actually X" and its reverse, "that
        phase is not real, drop it".

        Pixels changed this way are marked hand-set like any other manual
        edit — the assertion is the user's, not the measurement's.
        """
        with self._lock:
            if self._state is None:
                raise RuntimeError("No phase map loaded — run auto-classify first")
            st = self._state
            n_phases = len(st.phase_entries)
            for idx, name in ((from_phase_index, "from"), (to_phase_index, "to")):
                if idx != -1 and not (0 <= idx < n_phases):
                    raise ValueError(
                        f"{name}-phase index {idx} out of range (0..{n_phases - 1})")
            if from_phase_index == to_phase_index:
                return 0

            mask = st.phase_grid == int(from_phase_index)
            n = int(mask.sum())
            if n == 0:
                return 0
            self._snapshot("replace phase")

            st.phase_grid[mask] = int(to_phase_index)
            if st.locked_mask is None:
                st.locked_mask = np.zeros((st.n_rows, st.n_cols), dtype=bool)
            st.locked_mask[mask] = True
            st.score_grid[mask] = 1.0 if to_phase_index != -1 else 0.0
        self._autosave()
        return n

    def assign_mask(
        self,
        mask: np.ndarray,
        target_phase_index: int,
    ) -> int:
        """Paint an arbitrary 2D bool mask with a phase id.

        Generalised counterpart to :meth:`assign_region` — used by
        polygon / brush / lasso paint where the affected pixels don't
        form a rectangle. Same fail-loud rules: out-of-range phase
        index raises, no in-memory state is loaded raises, mismatched
        shape raises.

        Returns the number of pixels actually overwritten.
        """
        with self._lock:
            if self._state is None:
                raise RuntimeError("No phase map loaded — run auto-classify first")
            st = self._state
            if mask.shape != (st.n_rows, st.n_cols):
                raise ValueError(
                    f"mask shape {mask.shape} does not match phase grid "
                    f"shape {(st.n_rows, st.n_cols)}"
                )
            if target_phase_index != -1 and not (0 <= target_phase_index < len(st.phase_entries)):
                raise ValueError(
                    f"Phase index {target_phase_index} out of range "
                    f"(0..{len(st.phase_entries) - 1})"
                )
            bool_mask = mask.astype(bool, copy=False)
            n = int(bool_mask.sum())
            if n == 0:
                return 0
            # Snapshot only once the write is certain to happen, so a
            # rejected call cannot consume the user's one undo slot.
            self._snapshot("assign selection")
            st.phase_grid[bool_mask] = int(target_phase_index)
            if st.locked_mask is None:
                st.locked_mask = np.zeros((st.n_rows, st.n_cols), dtype=bool)
            st.locked_mask[bool_mask] = True
            st.score_grid[bool_mask] = 1.0 if target_phase_index != -1 else 0.0
        self._autosave()
        return n

    # --- Structures (2026-08-24) ---

    def _repaint_structures(self, st, sids) -> int:
        """Paint the given structures onto ``phase_grid`` from their names.

        Caller holds the lock and has already snapshotted. Pixels the user set
        by hand are left alone: a boundary move must not silently undo a
        decision the user made explicitly.
        """
        if st.structure_grid is None:
            return 0
        locked = (st.locked_mask if st.locked_mask is not None
                  else np.zeros((st.n_rows, st.n_cols), dtype=bool))
        n = 0
        for sid in sids:
            if not (0 <= sid < len(st.structure_phase)):
                continue
            m = (st.structure_grid == sid) & ~locked
            if not m.any():
                continue
            st.phase_grid[m] = int(st.structure_phase[sid])
            st.score_grid[m] = 0.0
            n += int(m.sum())
        return n

    def assign_structure(self, structure_id: int, target_phase_index: int) -> int:
        """Name one structure: every pixel of it becomes that phase.

        This is the point of the structure layer - one click instead of
        painting pixels. Unlike a hand paint it does NOT lock the pixels: the
        structure is the record of the decision, so a later boundary change
        keeps following it.
        """
        with self._lock:
            st = self._state
            if st is None:
                raise RuntimeError("No phase map loaded - run auto-classify first")
            if st.structure_grid is None:
                raise RuntimeError(
                    "This map has no structures - re-run the classification")
            if not (0 <= structure_id < len(st.structure_phase)):
                raise ValueError(
                    f"Structure {structure_id} out of range "
                    f"(0..{len(st.structure_phase) - 1})")
            if target_phase_index != -1 and not (
                    0 <= target_phase_index < len(st.phase_entries)):
                raise ValueError(
                    f"Phase index {target_phase_index} out of range "
                    f"(0..{len(st.phase_entries) - 1})")
            m = st.structure_grid == structure_id
            n = int(m.sum())
            if n == 0:
                return 0
            self._snapshot("name structure")
            st.structure_phase[structure_id] = int(target_phase_index)
            self._repaint_structures(st, [structure_id])
        self._autosave()
        return n

    def merge_structures(self, keep_id: int, drop_id: int) -> int:
        """Fold one structure into another.

        The most-needed boundary tool, because over-segmentation is the
        expected error: on SampleB the default splits one Si particle into
        three concentric rings (Si 24 / 36 / 52 at%) - the interaction volume
        makes a small particle read as a gradient rather than a plateau. How
        much rim belongs to the particle is a judgement, not a computation.

        Ids above ``drop_id`` shift down by one so the list stays dense.
        """
        with self._lock:
            st = self._state
            if st is None or st.structure_grid is None:
                raise RuntimeError("No structures on this map")
            n_s = len(st.structure_phase)
            for name, sid in (("keep_id", keep_id), ("drop_id", drop_id)):
                if not (0 <= sid < n_s):
                    raise ValueError(f"{name} {sid} out of range (0..{n_s - 1})")
            if keep_id == drop_id:
                return 0
            moved = int((st.structure_grid == drop_id).sum())
            self._snapshot("merge structures")
            st.structure_grid[st.structure_grid == drop_id] = keep_id
            st.structure_grid[st.structure_grid > drop_id] -= 1
            st.structure_phase.pop(drop_id)
            new_keep = keep_id - 1 if keep_id > drop_id else keep_id
            self._repaint_structures(st, [new_keep])
        self._autosave()
        return moved

    def split_structure(self, structure_id: int, n_parts: int = 2) -> int:
        """Re-cluster one structure's own pixels into ``n_parts``.

        Local, so the rest of the map is untouched. Raising the global cluster
        count instead would re-cut every other structure as well - which is
        exactly why a global k is not a usable boundary tool.

        The new parts inherit the original's phase; the user renames the ones
        that should differ. Returns the number of parts actually created.
        """
        from sklearn.cluster import KMeans

        with self._lock:
            st = self._state
            if st is None or st.structure_grid is None:
                raise RuntimeError("No structures on this map")
            if not (0 <= structure_id < len(st.structure_phase)):
                raise ValueError(
                    f"Structure {structure_id} out of range "
                    f"(0..{len(st.structure_phase) - 1})")
            n_parts = max(2, int(n_parts))
            feats = self._structure_features
            if feats is None:
                raise RuntimeError(
                    "The composition this map was built from is no longer in "
                    "memory - re-run the classification before splitting")
            m = (st.structure_grid == structure_id).ravel()
            if int(m.sum()) < n_parts:
                return 0
            labels = KMeans(n_clusters=n_parts, n_init=10,
                            random_state=0).fit_predict(feats[m])
            n_new = len(np.unique(labels))
            if n_new < 2:
                return 0

            self._snapshot("split structure")
            phase = st.structure_phase[structure_id]
            flat = st.structure_grid.ravel().copy()
            idx = np.nonzero(m)[0]
            new_ids = [structure_id]
            for _ in range(1, n_new):
                st.structure_phase.append(int(phase))
                new_ids.append(len(st.structure_phase) - 1)
            for part, sid in enumerate(new_ids):
                flat[idx[labels == part]] = sid
            st.structure_grid = flat.reshape(st.n_rows, st.n_cols)
            self._repaint_structures(st, new_ids)
        self._autosave()
        return n_new

    def grow_structure(self, structure_id: int, n_pixels: int) -> int:
        """Push a structure's boundary out (or in) by ``n_pixels``.

        Positive grows into whatever neighbours it; negative shrinks, and the
        vacated pixels go to the nearest other structure - never to nothing,
        which would punch holes in the map. Blind to the chemistry by design;
        :meth:`snap_structure_edges` is the one that looks at the data.
        """
        with self._lock:
            st = self._state
            if st is None or st.structure_grid is None:
                raise RuntimeError("No structures on this map")
            if not (0 <= structure_id < len(st.structure_phase)):
                raise ValueError(
                    f"Structure {structure_id} out of range "
                    f"(0..{len(st.structure_phase) - 1})")
            steps = int(n_pixels)
            if steps == 0:
                return 0
            before = st.structure_grid
            grid = before.copy()
            m = grid == structure_id
            if not m.any():
                return 0
            struct = ndimage.generate_binary_structure(2, 1)
            if steps > 0:
                grown = ndimage.binary_dilation(m, structure=struct,
                                                iterations=steps)
                grid[grown & (grid >= 0)] = structure_id
            else:
                shrunk = ndimage.binary_erosion(m, structure=struct,
                                                iterations=-steps,
                                                border_value=0)
                lost = m & ~shrunk
                if lost.any():
                    others = (grid >= 0) & ~m
                    if not others.any():
                        return 0
                    _, (ri, ci) = ndimage.distance_transform_edt(
                        ~others, return_indices=True)
                    grid[lost] = grid[ri[lost], ci[lost]]
            changed = int((grid != before).sum())
            if changed == 0:
                return 0
            self._snapshot("move boundary")
            st.structure_grid = grid
            self._repaint_structures(st, range(len(st.structure_phase)))
        self._autosave()
        return changed

    def snap_structure_edges(self, strength: float = 1.0) -> int:
        """Let every boundary relax onto the nearest strong chemistry edge.

        The other three boundary tools are blind to the data: merge and split
        change which pixels are grouped, grow moves an edge by a fixed amount.
        This one asks where the composition actually changes.

        Method: a watershed on the gradient magnitude of the smoothed
        composition, seeded by the structures' own eroded interiors. Interiors
        are guaranteed to keep their label, so a structure can never vanish or
        swap identity; only the contested band between them is re-decided, and
        it is decided by following the steepest chemical change.

        ``strength`` is the erosion radius in pixels: how wide a band around
        each boundary is put up for re-decision. 0 changes nothing.

        Deliberately NOT an active contour: a snake needs per-structure
        parameters and can cross itself, and nothing here would tell the user
        it had gone wrong. A seeded watershed either keeps the seeds or fails
        loudly.
        """
        from skimage.segmentation import watershed

        with self._lock:
            st = self._state
            if st is None or st.structure_grid is None:
                raise RuntimeError("No structures on this map")
            feats = self._structure_features
            if feats is None:
                raise RuntimeError(
                    "The composition this map was built from is no longer in "
                    "memory - re-run the classification before snapping")
            radius = int(round(max(0.0, float(strength))))
            if radius <= 0:
                return 0

            grid = st.structure_grid
            n_s = len(st.structure_phase)

            # Gradient magnitude over all elements: a boundary is wherever the
            # composition changes fastest, whichever element carries it.
            cube = feats.reshape(st.n_rows, st.n_cols, -1)
            grad = np.zeros((st.n_rows, st.n_cols), dtype=np.float64)
            for c in range(cube.shape[2]):
                gy, gx = np.gradient(cube[:, :, c])
                grad += gy * gy + gx * gx
            grad = np.sqrt(grad)

            struct = ndimage.generate_binary_structure(2, 1)
            markers = np.zeros_like(grid)
            for sid in range(n_s):
                m = grid == sid
                if not m.any():
                    continue
                core = ndimage.binary_erosion(m, structure=struct,
                                              iterations=radius, border_value=0)
                # A structure thinner than the band keeps its whole self as the
                # seed rather than disappearing.
                markers[core if core.any() else m] = sid + 1

            if not markers.any():
                return 0
            valid = grid >= 0
            new = watershed(grad, markers, mask=valid) - 1
            # Anything the watershed could not reach keeps what it had.
            new = np.where(new >= 0, new, grid).astype(np.int32)
            new[~valid] = -1

            changed = int((new != grid).sum())
            if changed == 0:
                return 0
            self._snapshot("snap boundaries")
            st.structure_grid = new
            self._repaint_structures(st, range(n_s))
        self._autosave()
        return changed

    # --- Persistence ---

    def _autosave(self) -> None:
        """Best-effort sidecar write — never raises into callers.

        A failed save is never worth aborting the in-memory set —
        the user's edit is still applied, they just won't have it
        across a backend restart. The exception is logged so a
        consistent failure (read-only filesystem, etc.) is at least
        diagnosable.
        """
        with self._lock:
            if self._state is None or not self._file_path:
                return
            file_path = self._file_path
        try:
            self.save_to_disk(file_path)
        except Exception:
            logger.exception("Phase-map sidecar autosave failed for %s", file_path)

    def save_to_disk(self, file_path: str) -> Optional[Path]:
        """Write the current state to ``<file_path>.phase_map.npz``.

        Returns the sidecar path on success, ``None`` if there is no
        state to save (the public API; ``_autosave`` already handled
        the silent path).

        Format: a single ``.npz`` with the int-grid + float-grid + an
        embedded JSON blob for the per-phase metadata. JSON keeps the
        loader free of pickle (which we'd otherwise need for the
        dataclass list and which has security implications when the
        sidecar comes from a shared location).
        """
        with self._lock:
            state = self._state
            if state is None:
                return None
            entries_payload = [
                {
                    "key": e.key,
                    "cif_filename": e.cif_filename,
                    "formula": e.formula,
                    "space_group": e.space_group,
                    "space_group_number": e.space_group_number,
                    "crystal_system": e.crystal_system,
                    "composition": dict(e.composition),
                    "elements": list(e.elements),
                }
                for e in state.phase_entries
            ]
            payload = {
                "schema": _SIDECAR_SCHEMA,
                "n_rows": state.n_rows,
                "n_cols": state.n_cols,
                "tolerance": state.tolerance,
                    "min_score": state.min_score,
                "entries": entries_payload,
                # Which structure carries which phase. Small (one int per
                # structure), so it rides in the JSON rather than as another
                # array. The structure GRID is an array below.
                "structure_phase": list(state.structure_phase),
            }
            sidecar = _sidecar_path_for(file_path)
            np.savez_compressed(
                str(sidecar),
                phase_grid=state.phase_grid,
                score_grid=state.score_grid,
                # Optional locked_mask: store as empty array when unset
                # so the loader can detect "no manual edits" cheaply.
                locked_mask=(state.locked_mask if state.locked_mask is not None
                             else np.zeros((0, 0), dtype=bool)),
                # Same empty-array convention as locked_mask: a map from
                # before structures existed simply has none.
                structure_grid=(state.structure_grid
                                if state.structure_grid is not None
                                else np.zeros((0, 0), dtype=np.int32)),
                meta=np.array(json.dumps(payload), dtype=str),
            )
        return sidecar

    def load_from_disk(self, file_path: str) -> bool:
        """Restore state from a sidecar if one exists. Returns True on hit.

        Schema mismatch / corrupt file / missing file all return False
        without touching the current state — callers (e.g. open_file)
        treat False as "nothing to restore" and continue normally.
        """
        sidecar = _sidecar_path_for(file_path)
        if not sidecar.is_file():
            return False
        try:
            with np.load(str(sidecar), allow_pickle=False) as data:
                meta_raw = data["meta"]
                # ``np.array(json_str, dtype=str)`` produces a 0-d
                # array; ``.item()`` unwraps it back to a Python str.
                meta = json.loads(meta_raw.item() if meta_raw.ndim == 0 else str(meta_raw))
                if meta.get("schema") != _SIDECAR_SCHEMA:
                    logger.info(
                        "Phase-map sidecar %s has schema %s, expected %s — ignoring.",
                        sidecar, meta.get("schema"), _SIDECAR_SCHEMA,
                    )
                    return False
                phase_grid = data["phase_grid"]
                score_grid = data["score_grid"]
                locked_arr = data["locked_mask"]
                struct_arr = (data["structure_grid"]
                              if "structure_grid" in data.files
                              else np.zeros((0, 0), dtype=np.int32))
        except Exception:
            logger.exception("Failed to load phase-map sidecar %s", sidecar)
            return False

        try:
            entries = [
                CifPhaseEntry(
                    key=e["key"],
                    cif_filename=e["cif_filename"],
                    formula=e.get("formula", ""),
                    space_group=e.get("space_group", ""),
                    space_group_number=e.get("space_group_number"),
                    crystal_system=e.get("crystal_system", ""),
                    composition=dict(e["composition"]),
                    elements=list(e["elements"]),
                )
                for e in meta["entries"]
            ]
        except KeyError:
            logger.exception(
                "Phase-map sidecar %s entries are malformed — ignoring.", sidecar
            )
            return False

        n_rows = int(meta["n_rows"])
        n_cols = int(meta["n_cols"])
        if phase_grid.shape != (n_rows, n_cols):
            logger.warning(
                "Phase-map sidecar %s: phase_grid shape %s != meta shape %s — ignoring.",
                sidecar, phase_grid.shape, (n_rows, n_cols),
            )
            return False

        locked = locked_arr if locked_arr.size > 0 else None
        structures = struct_arr if struct_arr.size > 0 else None
        struct_phase = list(meta.get("structure_phase") or [])
        if structures is not None:
            # A grid whose ids do not fit the assignment list would index out
            # of range on the first repaint. Refusing the structures - not the
            # whole map - keeps the classification usable.
            n_ids = int(structures.max()) + 1 if structures.size else 0
            if structures.shape != (n_rows, n_cols) or n_ids > len(struct_phase):
                logger.warning(
                    "Phase-map sidecar %s: structure grid does not match its "
                    "assignment list - dropping the structures, keeping the map.",
                    sidecar,
                )
                structures, struct_phase = None, []
        with self._lock:
            self._state = PhaseMapState(
                phase_grid=phase_grid.astype(np.int32, copy=True),
                score_grid=score_grid.astype(np.float32, copy=True),
                phase_entries=entries,
                n_rows=n_rows,
                n_cols=n_cols,
                tolerance=float(meta.get("tolerance", 15.0)),
                min_score=float(meta.get("min_score", 0.3)),
                locked_mask=locked.astype(bool, copy=True) if locked is not None else None,
                structure_grid=(structures.astype(np.int32, copy=True)
                                if structures is not None else None),
                structure_phase=struct_phase,
            )
            # Splitting and snapping need the composition, which is derived
            # data and deliberately not in the sidecar. Both fail loud with a
            # "re-run the classification" message rather than guessing.
            self._structure_features = None
            self._file_path = file_path
        logger.info("Phase-map sidecar restored from %s (%d phases, %dx%d)",
                    sidecar, len(entries), n_rows, n_cols)
        return True

    # --- Read API for indexing (M5) and visualisation (M3) ---

    def phase_summary(self) -> List[Dict]:
        """Per-phase counts + percentage for the legend / phase list UI."""
        with self._lock:
            if self._state is None:
                return []
            st = self._state
            total = st.n_rows * st.n_cols
            # Bincount over a positive-shifted grid so -1 lands at index 0.
            shifted = (st.phase_grid + 1).ravel()
            counts = np.bincount(shifted, minlength=len(st.phase_entries) + 1)
            unclassified = int(counts[0])
            summary: List[Dict] = []
            for i, entry in enumerate(st.phase_entries):
                n = int(counts[i + 1])
                if n == 0:
                    continue  # skip phases with no pixels (not needed in the legend)
                summary.append({
                    "phase_index": i,
                    "cif_filename": entry.cif_filename,
                    "formula": entry.formula,
                    "space_group": entry.space_group,
                    "space_group_number": entry.space_group_number,
                    "crystal_system": entry.crystal_system,
                    "elements": list(entry.elements),
                    "n_pixels": n,
                    "percentage": round(n / total * 100, 2) if total > 0 else 0.0,
                })
            summary.append({
                "phase_index": -1,
                "cif_filename": "",
                "formula": "",
                "space_group": "",
                "crystal_system": "",
                "n_pixels": unclassified,
                "percentage": round(unclassified / total * 100, 2) if total > 0 else 0.0,
                "is_unclassified": True,
            })
            return summary

    def get_phase_masks(self) -> Tuple[List[CifPhaseEntry], Dict[int, np.ndarray]]:
        """Return ``({phase_index: bool_mask_2d}, ordered_phase_entries)``.

        Used by the indexing pipeline (M5) to drive a per-phase run:
        for each entry that has a non-empty mask, run indexing only on
        those pixels with that phase as the candidate. Unclassified
        pixels are excluded entirely — those need to be either
        manually assigned or left uniform-tested in a separate pass.
        """
        with self._lock:
            if self._state is None:
                return [], {}
            st = self._state
            masks: Dict[int, np.ndarray] = {}
            for i in range(len(st.phase_entries)):
                m = st.phase_grid == i
                if m.any():
                    masks[i] = m
            return list(st.phase_entries), masks


def phase_palette(n: int) -> List[Tuple[int, int, int]]:
    """``n`` visually distinct RGB colours, deterministic by POSITION.

    Kept for callers that have no names to key on. Prefer
    :func:`phase_colours_for` — a positional palette means unticking one
    phase recolours the others, so two runs of the same sample are not
    visually comparable.
    """
    import colorsys
    golden = 0.618033988749895
    colours: List[Tuple[int, int, int]] = []
    h = 0.13  # offset away from pure red
    for i in range(n):
        h = (h + golden) % 1.0
        s = 0.65 if i % 2 else 0.85
        v = 0.85 if i % 2 else 0.95
        r, g, b = colorsys.hsv_to_rgb(h, s, v)
        colours.append((int(r * 255), int(g * 255), int(b * 255)))
    return colours


def _norm_phase_name(name: str) -> str:
    """The key both pages agree on.

    The EBSD phase map names a phase by the file STEM
    (``routes/indexing._smart_phase_name_from_path``), the EDS candidate
    list carries the full filename. Dropping the ``.cif`` extension makes
    "Al.cif" and "Al" the same phase, so the default colour matches across
    pages and one override covers both.
    """
    n = (name or "").strip()
    if n.lower().endswith(".cif"):
        n = n[:-4]
    return n.lower()


def phase_colours_for(
    names: List[str], overrides: Optional[Dict[str, str]] = None,
    priority: Optional[List[int]] = None,
) -> List[Tuple[int, int, int]]:
    """Colours keyed on the phase NAME, plus the user's own choices.

    Two reasons this replaces the positional palette:

    1. Position is not identity. The candidate list depends on which phases
       the user ticked and on which elements the file measured, so unticking
       one phase used to recolour unrelated ones - measured: removing a
       single entry recoloured 23 of 29, and colours SWAPPED between phases.
       Two runs of the same sample were not comparable, which is the one
       thing a phase map has to be.
    2. The same phase should look the same everywhere in the app. This uses
       the identical name hash and Dracula palette as the EBSD phase map
       (``routes/phase_map.stable_color_idx``), so Al is the same green on
       both pages, and the user's saved overrides - already persisted by the
       frontend for the EBSD side - apply here too.
    """
    from backend.api.routes.phase_map import PHASE_COLORS, stable_color_idx

    def _stem(n: str) -> str:
        n = (n or "").strip()
        return n[:-4] if n.lower().endswith(".cif") else n

    ov = {_norm_phase_name(k): v for k, v in (overrides or {}).items()}
    stems = [_stem(n) for n in names]

    # Who gets shade 0 when two phases share a palette slot. The caller
    # passes the phases the map actually SHOWS first: a candidate that
    # covers no pixel never appears on the map, so it must not push a
    # visible phase off the colour the EBSD page paints for it.
    order = list(priority) if priority is not None else list(range(len(names)))
    seen_order = set(order)
    order += [i for i in range(len(names)) if i not in seen_order]

    used: set = set()
    out: List[Optional[Tuple[int, int, int]]] = [None] * len(names)
    for i in order:
        stem = stems[i]
        hexed = ov.get(stem.lower())
        if hexed:
            rgb = _parse_hex(hexed)
            if rgb is not None:
                out[i] = rgb
                continue
        if not stem:
            base = PHASE_COLORS[i % len(PHASE_COLORS)]
        else:
            base = PHASE_COLORS[stable_color_idx(stem)]
        rgb = tuple(int(c * 255) for c in base)
        # The palette has eight slots and a library can hold far more phases.
        # Shade 0 is the untouched slot colour, so a phase that does not
        # collide gets EXACTLY what the EBSD phase map paints; only a phase
        # that would otherwise be indistinguishable from an earlier one is
        # moved, and then by a fixed ladder so the result stays deterministic.
        for factor in _SHADE_LADDER:
            cand = tuple(int(max(0, min(255, round(c * factor)))) for c in rgb)
            if cand not in used:
                rgb = cand
                break
        else:
            rgb = tuple(int(max(0, min(255, round(c * _SHADE_LADDER[-1])))) for c in rgb)
        used.add(rgb)
        out[i] = rgb
    return [c for c in out if c is not None]


# Alternating lighter/darker so a shifted phase stays legible on the dark
# canvas either way. Index 0 is 1.0: no collision means no change.
_SHADE_LADDER = (1.0, 0.70, 1.30, 0.55, 1.45, 0.42, 0.85, 1.15)


def _parse_hex(value: str) -> Optional[Tuple[int, int, int]]:
    """``#rrggbb`` -> RGB. Returns None for anything else, so a malformed
    override falls back to the stable colour instead of raising."""
    v = (value or "").strip().lstrip("#")
    if len(v) != 6:
        return None
    try:
        return (int(v[0:2], 16), int(v[2:4], 16), int(v[4:6], 16))
    except ValueError:
        return None


def _shade_priority(state: PhaseMapState) -> List[int]:
    """Phase indices, the ones the map shows first and the biggest first.

    Only matters when more phases than palette slots share a slot: whoever
    comes first keeps the untouched colour, which is the one the EBSD phase
    map paints. A candidate covering no pixel is invisible on the map, so it
    yields.
    """
    counts = np.bincount(
        state.phase_grid[state.phase_grid >= 0].ravel(),
        minlength=len(state.phase_entries),
    ) if state.phase_grid.size else np.zeros(len(state.phase_entries), dtype=int)
    return sorted(range(len(state.phase_entries)), key=lambda i: (-int(counts[i]), i))


#: Colours for the structure view. A structure is not a phase - it has no
#: name yet - so it deliberately does NOT borrow the phase palette: seeing
#: "the green one" on both views while they mean different things is worse
#: than two unrelated colour schemes.
#:
#: Golden-angle hue walk at fixed saturation and value, so any number of
#: structures stays distinguishable and structure 3 is always the same colour
#: whether the map has five structures or fifteen.
_STRUCTURE_GOLDEN_ANGLE = 0.61803398875


def structure_color(structure_id: int) -> Tuple[int, int, int]:
    """RGB for one structure id. Stable, and independent of how many exist."""
    import colorsys

    h = (0.08 + _STRUCTURE_GOLDEN_ANGLE * int(structure_id)) % 1.0
    # Alternate value slightly so neighbouring ids differ in brightness too,
    # which survives being printed in greyscale.
    v = 0.95 if int(structure_id) % 2 == 0 else 0.78
    r, g, b = colorsys.hsv_to_rgb(h, 0.62, v)
    return (int(r * 255), int(g * 255), int(b * 255))


def structure_color_hex(structure_id: int) -> str:
    r, g, b = structure_color(structure_id)
    return f"#{r:02x}{g:02x}{b:02x}"


def render_structure_map_to_base64(state: PhaseMapState) -> str:
    """PNG of the structure grid, one colour per structure.

    Same dark grey for "no data" as the phase map, so the two views line up
    visually and only the coloured regions differ.
    """
    import base64
    import io
    from PIL import Image

    if state.structure_grid is None:
        raise ValueError("This map has no structures")

    rgb = np.zeros((state.n_rows, state.n_cols, 3), dtype=np.uint8)
    rgb[...] = (60, 60, 60)
    for sid in range(len(state.structure_phase)):
        m = state.structure_grid == sid
        if m.any():
            rgb[m] = structure_color(sid)

    img = Image.fromarray(rgb)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode("ascii")


def render_phase_map_to_base64(
    state: PhaseMapState, overrides: Optional[Dict[str, str]] = None,
) -> str:
    """Encode the phase grid as a PNG with one fixed colour per phase.

    Unclassified pixels (-1) are rendered as a dark grey so the
    visualisation never confuses "we tested this pixel and gave up"
    with "we coloured it the same as some real phase". Returns the
    raw base64 string (no ``data:`` prefix) — same format every other
    image-returning endpoint already uses.
    """
    import base64
    import io
    from PIL import Image  # already a project dep via image_utils

    palette = phase_colours_for(
        [e.cif_filename for e in state.phase_entries], overrides,
        _shade_priority(state))
    rgb = np.zeros((state.n_rows, state.n_cols, 3), dtype=np.uint8)
    rgb[...] = (60, 60, 60)  # unclassified

    for i, colour in enumerate(palette):
        mask = state.phase_grid == i
        if not mask.any():
            continue
        rgb[mask] = colour

    # mode= is deprecated in Pillow 13; the array shape (H, W, 3) is
    # already unambiguous, so omitting the mode is the right call.
    img = Image.fromarray(rgb)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode("ascii")


def palette_hex_for_state(
    state: PhaseMapState, overrides: Optional[Dict[str, str]] = None,
) -> List[str]:
    """Hex strings for the legend — one per ``phase_entries`` slot.

    Keyed on the phase name, so the legend, the rendered map and the EBSD
    phase map all agree, and the user's saved colour choices apply.
    """
    names = [e.cif_filename for e in state.phase_entries]
    return [f"#{r:02x}{g:02x}{b:02x}"
            for (r, g, b) in phase_colours_for(
                names, overrides, _shade_priority(state))]


# Singleton — one phase map per backend process is enough for now.
# If we ever want N concurrent files in one backend we can promote
# this to a ``Dict[file_path, PhaseMapStore]``, but every other piece
# of the EDS stack is already single-file (extractor, calibration
# store) so matching that keeps things consistent.
_STORE = PhaseMapStore()


def get_phase_map_store() -> PhaseMapStore:
    return _STORE
