// Standard periodic table layout: 18 columns, 7 rows + 2 f-block rows
// row/col are 1-based grid positions
const ELEMENTS = [
  // Row 1
  { z: 1, symbol: 'H', name: 'Hydrogen', row: 1, col: 1 },
  { z: 2, symbol: 'He', name: 'Helium', row: 1, col: 18 },
  // Row 2
  { z: 3, symbol: 'Li', name: 'Lithium', row: 2, col: 1 },
  { z: 4, symbol: 'Be', name: 'Beryllium', row: 2, col: 2 },
  { z: 5, symbol: 'B', name: 'Boron', row: 2, col: 13 },
  { z: 6, symbol: 'C', name: 'Carbon', row: 2, col: 14 },
  { z: 7, symbol: 'N', name: 'Nitrogen', row: 2, col: 15 },
  { z: 8, symbol: 'O', name: 'Oxygen', row: 2, col: 16 },
  { z: 9, symbol: 'F', name: 'Fluorine', row: 2, col: 17 },
  { z: 10, symbol: 'Ne', name: 'Neon', row: 2, col: 18 },
  // Row 3
  { z: 11, symbol: 'Na', name: 'Sodium', row: 3, col: 1 },
  { z: 12, symbol: 'Mg', name: 'Magnesium', row: 3, col: 2 },
  { z: 13, symbol: 'Al', name: 'Aluminium', row: 3, col: 13 },
  { z: 14, symbol: 'Si', name: 'Silicon', row: 3, col: 14 },
  { z: 15, symbol: 'P', name: 'Phosphorus', row: 3, col: 15 },
  { z: 16, symbol: 'S', name: 'Sulfur', row: 3, col: 16 },
  { z: 17, symbol: 'Cl', name: 'Chlorine', row: 3, col: 17 },
  { z: 18, symbol: 'Ar', name: 'Argon', row: 3, col: 18 },
  // Row 4
  { z: 19, symbol: 'K', name: 'Potassium', row: 4, col: 1 },
  { z: 20, symbol: 'Ca', name: 'Calcium', row: 4, col: 2 },
  { z: 21, symbol: 'Sc', name: 'Scandium', row: 4, col: 3 },
  { z: 22, symbol: 'Ti', name: 'Titanium', row: 4, col: 4 },
  { z: 23, symbol: 'V', name: 'Vanadium', row: 4, col: 5 },
  { z: 24, symbol: 'Cr', name: 'Chromium', row: 4, col: 6 },
  { z: 25, symbol: 'Mn', name: 'Manganese', row: 4, col: 7 },
  { z: 26, symbol: 'Fe', name: 'Iron', row: 4, col: 8 },
  { z: 27, symbol: 'Co', name: 'Cobalt', row: 4, col: 9 },
  { z: 28, symbol: 'Ni', name: 'Nickel', row: 4, col: 10 },
  { z: 29, symbol: 'Cu', name: 'Copper', row: 4, col: 11 },
  { z: 30, symbol: 'Zn', name: 'Zinc', row: 4, col: 12 },
  { z: 31, symbol: 'Ga', name: 'Gallium', row: 4, col: 13 },
  { z: 32, symbol: 'Ge', name: 'Germanium', row: 4, col: 14 },
  { z: 33, symbol: 'As', name: 'Arsenic', row: 4, col: 15 },
  { z: 34, symbol: 'Se', name: 'Selenium', row: 4, col: 16 },
  { z: 35, symbol: 'Br', name: 'Bromine', row: 4, col: 17 },
  { z: 36, symbol: 'Kr', name: 'Krypton', row: 4, col: 18 },
  // Row 5
  { z: 37, symbol: 'Rb', name: 'Rubidium', row: 5, col: 1 },
  { z: 38, symbol: 'Sr', name: 'Strontium', row: 5, col: 2 },
  { z: 39, symbol: 'Y', name: 'Yttrium', row: 5, col: 3 },
  { z: 40, symbol: 'Zr', name: 'Zirconium', row: 5, col: 4 },
  { z: 41, symbol: 'Nb', name: 'Niobium', row: 5, col: 5 },
  { z: 42, symbol: 'Mo', name: 'Molybdenum', row: 5, col: 6 },
  { z: 43, symbol: 'Tc', name: 'Technetium', row: 5, col: 7 },
  { z: 44, symbol: 'Ru', name: 'Ruthenium', row: 5, col: 8 },
  { z: 45, symbol: 'Rh', name: 'Rhodium', row: 5, col: 9 },
  { z: 46, symbol: 'Pd', name: 'Palladium', row: 5, col: 10 },
  { z: 47, symbol: 'Ag', name: 'Silver', row: 5, col: 11 },
  { z: 48, symbol: 'Cd', name: 'Cadmium', row: 5, col: 12 },
  { z: 49, symbol: 'In', name: 'Indium', row: 5, col: 13 },
  { z: 50, symbol: 'Sn', name: 'Tin', row: 5, col: 14 },
  { z: 51, symbol: 'Sb', name: 'Antimony', row: 5, col: 15 },
  { z: 52, symbol: 'Te', name: 'Tellurium', row: 5, col: 16 },
  { z: 53, symbol: 'I', name: 'Iodine', row: 5, col: 17 },
  { z: 54, symbol: 'Xe', name: 'Xenon', row: 5, col: 18 },
  // Row 6
  { z: 55, symbol: 'Cs', name: 'Caesium', row: 6, col: 1 },
  { z: 56, symbol: 'Ba', name: 'Barium', row: 6, col: 2 },
  { z: 72, symbol: 'Hf', name: 'Hafnium', row: 6, col: 4 },
  { z: 73, symbol: 'Ta', name: 'Tantalum', row: 6, col: 5 },
  { z: 74, symbol: 'W', name: 'Tungsten', row: 6, col: 6 },
  { z: 75, symbol: 'Re', name: 'Rhenium', row: 6, col: 7 },
  { z: 76, symbol: 'Os', name: 'Osmium', row: 6, col: 8 },
  { z: 77, symbol: 'Ir', name: 'Iridium', row: 6, col: 9 },
  { z: 78, symbol: 'Pt', name: 'Platinum', row: 6, col: 10 },
  { z: 79, symbol: 'Au', name: 'Gold', row: 6, col: 11 },
  { z: 80, symbol: 'Hg', name: 'Mercury', row: 6, col: 12 },
  { z: 81, symbol: 'Tl', name: 'Thallium', row: 6, col: 13 },
  { z: 82, symbol: 'Pb', name: 'Lead', row: 6, col: 14 },
  { z: 83, symbol: 'Bi', name: 'Bismuth', row: 6, col: 15 },
  { z: 84, symbol: 'Po', name: 'Polonium', row: 6, col: 16 },
  { z: 85, symbol: 'At', name: 'Astatine', row: 6, col: 17 },
  { z: 86, symbol: 'Rn', name: 'Radon', row: 6, col: 18 },
  // Row 7
  { z: 87, symbol: 'Fr', name: 'Francium', row: 7, col: 1 },
  { z: 88, symbol: 'Ra', name: 'Radium', row: 7, col: 2 },
  { z: 104, symbol: 'Rf', name: 'Rutherfordium', row: 7, col: 4 },
  { z: 105, symbol: 'Db', name: 'Dubnium', row: 7, col: 5 },
  { z: 106, symbol: 'Sg', name: 'Seaborgium', row: 7, col: 6 },
  { z: 107, symbol: 'Bh', name: 'Bohrium', row: 7, col: 7 },
  { z: 108, symbol: 'Hs', name: 'Hassium', row: 7, col: 8 },
  { z: 109, symbol: 'Mt', name: 'Meitnerium', row: 7, col: 9 },
  { z: 110, symbol: 'Ds', name: 'Darmstadtium', row: 7, col: 10 },
  { z: 111, symbol: 'Rg', name: 'Roentgenium', row: 7, col: 11 },
  { z: 112, symbol: 'Cn', name: 'Copernicium', row: 7, col: 12 },
  { z: 113, symbol: 'Nh', name: 'Nihonium', row: 7, col: 13 },
  { z: 114, symbol: 'Fl', name: 'Flerovium', row: 7, col: 14 },
  { z: 115, symbol: 'Mc', name: 'Moscovium', row: 7, col: 15 },
  { z: 116, symbol: 'Lv', name: 'Livermorium', row: 7, col: 16 },
  { z: 117, symbol: 'Ts', name: 'Tennessine', row: 7, col: 17 },
  { z: 118, symbol: 'Og', name: 'Oganesson', row: 7, col: 18 },
  // Lanthanides (row 8, cols 4-18)
  { z: 57, symbol: 'La', name: 'Lanthanum', row: 8, col: 4 },
  { z: 58, symbol: 'Ce', name: 'Cerium', row: 8, col: 5 },
  { z: 59, symbol: 'Pr', name: 'Praseodymium', row: 8, col: 6 },
  { z: 60, symbol: 'Nd', name: 'Neodymium', row: 8, col: 7 },
  { z: 61, symbol: 'Pm', name: 'Promethium', row: 8, col: 8 },
  { z: 62, symbol: 'Sm', name: 'Samarium', row: 8, col: 9 },
  { z: 63, symbol: 'Eu', name: 'Europium', row: 8, col: 10 },
  { z: 64, symbol: 'Gd', name: 'Gadolinium', row: 8, col: 11 },
  { z: 65, symbol: 'Tb', name: 'Terbium', row: 8, col: 12 },
  { z: 66, symbol: 'Dy', name: 'Dysprosium', row: 8, col: 13 },
  { z: 67, symbol: 'Ho', name: 'Holmium', row: 8, col: 14 },
  { z: 68, symbol: 'Er', name: 'Erbium', row: 8, col: 15 },
  { z: 69, symbol: 'Tm', name: 'Thulium', row: 8, col: 16 },
  { z: 70, symbol: 'Yb', name: 'Ytterbium', row: 8, col: 17 },
  { z: 71, symbol: 'Lu', name: 'Lutetium', row: 8, col: 18 },
  // Actinides (row 9, cols 4-18)
  { z: 89, symbol: 'Ac', name: 'Actinium', row: 9, col: 4 },
  { z: 90, symbol: 'Th', name: 'Thorium', row: 9, col: 5 },
  { z: 91, symbol: 'Pa', name: 'Protactinium', row: 9, col: 6 },
  { z: 92, symbol: 'U', name: 'Uranium', row: 9, col: 7 },
  { z: 93, symbol: 'Np', name: 'Neptunium', row: 9, col: 8 },
  { z: 94, symbol: 'Pu', name: 'Plutonium', row: 9, col: 9 },
  { z: 95, symbol: 'Am', name: 'Americium', row: 9, col: 10 },
  { z: 96, symbol: 'Cm', name: 'Curium', row: 9, col: 11 },
  { z: 97, symbol: 'Bk', name: 'Berkelium', row: 9, col: 12 },
  { z: 98, symbol: 'Cf', name: 'Californium', row: 9, col: 13 },
  { z: 99, symbol: 'Es', name: 'Einsteinium', row: 9, col: 14 },
  { z: 100, symbol: 'Fm', name: 'Fermium', row: 9, col: 15 },
  { z: 101, symbol: 'Md', name: 'Mendelevium', row: 9, col: 16 },
  { z: 102, symbol: 'No', name: 'Nobelium', row: 9, col: 17 },
  { z: 103, symbol: 'Lr', name: 'Lawrencium', row: 9, col: 18 },
];

// Placeholder markers for the main table (La*/Ac* arrows)
const F_BLOCK_MARKERS = [
  { label: 'La-Lu', row: 6, col: 3 },
  { label: 'Ac-Lr', row: 7, col: 3 },
];

export { ELEMENTS, F_BLOCK_MARKERS };
