"""Shared fixtures for GPU spherical indexing tests.

The oracle file is generated by ``scripts/generate_oracle.py`` and is gitignored
(per-machine artefact). Its sha256 IS committed and validated by every test
session — that prevents Ralph from silently rewriting the oracle to make tests
pass.

Tests must NOT reference ``Database/EBSD_SHT_Database/*`` paths directly. Use
the embedded SHT bytes from the oracle instead via the ``sht_path`` fixture.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import h5py
import numpy as np
import pytest
import torch


ORACLE_PATH = Path(__file__).parent / "data" / "reference_oracle.h5"
ORACLE_SHA_PATH = ORACLE_PATH.with_suffix(".sha256")


@pytest.fixture(scope="session")
def oracle():
    """Open the reference oracle, validate sha256, yield the h5py.File."""
    if not ORACLE_PATH.is_file():
        pytest.skip(
            f"Oracle not found at {ORACLE_PATH}. Generate with:\n"
            f"  python scripts/generate_oracle.py --help"
        )
    if not ORACLE_SHA_PATH.is_file():
        pytest.fail(
            f"Oracle hash file missing: {ORACLE_SHA_PATH}. "
            "Regenerate the oracle to produce a fresh sha256 lock."
        )
    expected_sha = ORACLE_SHA_PATH.read_text().split()[0]
    actual_sha = hashlib.sha256(ORACLE_PATH.read_bytes()).hexdigest()
    if expected_sha != actual_sha:
        pytest.fail(
            "Oracle integrity violation!\n"
            f"  expected sha256: {expected_sha}\n"
            f"  actual sha256:   {actual_sha}\n"
            "If this is intentional, regenerate the oracle and update .sha256."
        )

    with h5py.File(ORACLE_PATH, "r") as f:
        yield f


@pytest.fixture(scope="session")
def oracle_meta(oracle):
    """Parsed JSON metadata embedded in the oracle's root attrs."""
    return json.loads(oracle.attrs["meta_json"])


@pytest.fixture
def sht_path(oracle, tmp_path):
    """Materialize the embedded SHT bytes to a tmp_path. Returns the path string.

    Each test gets its own copy in its own tmp_path — no cross-test pollution.
    """
    sht_bytes = bytes(oracle["embedded_sht_bytes"][()])
    sht_filename = oracle["embedded_sht_filename"][()]
    if isinstance(sht_filename, bytes):
        sht_filename = sht_filename.decode("utf-8")
    target = tmp_path / sht_filename
    target.write_bytes(sht_bytes)
    return str(target)


@pytest.fixture(scope="session")
def device():
    """The torch device for tests. Prefer CUDA, fall back to CPU.

    NOTE: when CUDA is not available, tests still run but the "schnell" goal
    of the feature is not validated. Performance gates may then be skipped.
    """
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


@pytest.fixture(scope="session")
def oracle_h5oina(oracle_meta):
    """Path to the source H5OINA used to generate the oracle."""
    p = Path(oracle_meta["h5oina_source"])
    if not p.is_file():
        pytest.skip(f"Oracle source H5OINA not found at {p}")
    return str(p)


@pytest.fixture(scope="session")
def detector_params(oracle_meta):
    """Detector params dict in the format used by gpu_spherical_index_patterns."""
    keys = (
        "n_rows", "n_cols", "pat_width", "pat_height", "pixel_size",
        "tilt", "binning", "step_x", "step_y", "pc_x", "pc_y", "pc_z",
    )
    return {**{k: oracle_meta[k] for k in keys}, "vendor": oracle_meta["vendor"]}
