"""Iter-14 diagnostic test: dump cc-peak (a,b,c) for synthetic rotations.

If the cc-peak for X30 is at the predicted (a, b, c), the bug is in the DECODE
formula. If the peak is somewhere else, the bug is in the detector->sphere /
SHT pipeline upstream of decode.
"""
from __future__ import annotations

import json
import math
import sys
import tempfile
from pathlib import Path

import h5py
import numpy as np
import pytest
import torch

# These probes open the reference oracle themselves instead of taking the
# `oracle` fixture, so they need the same guard: no oracle, no run. The
# file is not in the repository (sha256-locked, generated by
# scripts/generate_oracle.py).
from tests.data_deps import SPHERICAL_ORACLE, requires

pytestmark = requires(SPHERICAL_ORACLE)


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "scripts"))


def _predict_peak(phi1_deg, Phi_deg, phi2_deg, L=68):
    size = 2 * L - 1
    off = L - 1
    scale = 2 * math.pi / size
    phi1, Phi, phi2 = (math.radians(x) for x in (phi1_deg, Phi_deg, phi2_deg))
    alpha = (phi1 - math.pi / 2) % (2 * math.pi)
    beta  = Phi
    gamma = (phi2 + math.pi / 2) % (2 * math.pi)
    a = int(round((alpha / scale + off) % size))
    b = int(round(beta / scale))
    c = int(round((off - gamma / scale) % size))
    return a, b, c


@pytest.mark.parametrize(
    "label,R",
    [
        ("identity", (0,  0,  0)),
        ("Z30",      (30, 0,  0)),
        ("Z90",      (90, 0,  0)),
        ("X30",      (0,  30, 0)),
        ("X90",      (0,  90, 0)),
        ("ZXZ_30_45_15", (30, 45, 15)),
    ],
)
def test_cc_peak_dump(label, R):
    from backend.spherical_gpu.pipeline.detector import DetectorGeometry
    from backend.spherical_gpu.pipeline.indexer import Tier1Indexer
    from backend.spherical_gpu.pipeline.sht_io import read_sht_master
    from backend.spherical_gpu.pipeline.preprocessing import gausbckg, nregions
    from backend.spherical_gpu._math.sht_cc import rs2cc_
    from synth_pattern_forward_rotated import synth_pattern_via_forward_rotated

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    oracle_path = PROJECT_ROOT / "tests/test_spherical_gpu/data/reference_oracle.h5"
    with h5py.File(oracle_path, "r") as f:
        meta = json.loads(f.attrs["meta_json"])
        sht_bytes = bytes(f["embedded_sht_bytes"][()])
    tmp = tempfile.NamedTemporaryFile(suffix=".sht", delete=False)
    tmp.write(sht_bytes); tmp.close()

    detector_params = {k: meta[k] for k in (
        "n_rows", "n_cols", "pat_width", "pat_height", "pixel_size",
        "tilt", "binning", "step_x", "step_y", "pc_x", "pc_y", "pc_z", "vendor",
    )}
    geom = DetectorGeometry.from_params(detector_params, device=device)
    master = read_sht_master(tmp.name, device=device)
    indexer = Tier1Indexer(geom, master, device, bandwidth=meta["bandwidth"])
    L = indexer.bandwidth
    size = 2 * L - 1

    pat_np = synth_pattern_via_forward_rotated(master, geom, R, fine_n=400)
    pat_t = torch.from_numpy(pat_np[None, :, :]).to(device).float()

    prep = nregions(gausbckg(pat_t), n=10)
    pattern_coefs = indexer._direct_sht_coefs(prep)
    cc = rs2cc_(L, pattern_coefs, indexer._master_coefs, indexer._wigner_table)
    rDen = indexer._rDen_vol.to(device)
    nc_vol = (cc.real.float() * rDen)[0]   # (size, size, size)

    flat = nc_vol.reshape(-1).argmax().item()
    a_obs = flat // (size * size)
    rem = flat % (size * size)
    b_obs = rem // size
    c_obs = rem % size
    cc_at_peak = float(nc_vol[a_obs, b_obs, c_obs].item())

    a_pred, b_pred, c_pred = _predict_peak(*R, L=L)
    cc_at_predicted = float(nc_vol[a_pred, b_pred, c_pred].item())

    print(
        f"\n[{label}] target_zxz={R}  predicted=({a_pred},{b_pred},{c_pred}) "
        f"observed=({a_obs},{b_obs},{c_obs})  "
        f"cc_at_peak={cc_at_peak:.4f}  cc_at_predicted={cc_at_predicted:.4f}"
    )

    # Always pass — purely diagnostic
    assert cc_at_peak >= cc_at_predicted - 1e-3
