"""Iter-14 final bug isolation: which downsample method minimizes per-cell
diff vs EMSphInx's DCT-based Image::Rescaler?

Test 5 candidates on the same input pattern + GL grid coords:
1. adaptive_avg_pool2d (current)
2. F.interpolate area
3. F.interpolate bilinear (anti-aliased)
4. F.interpolate bicubic (anti-aliased)
5. No downsample at all (baseline reference)
"""
from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

import h5py
import numpy as np
import torch
import torch.nn.functional as F

# These probes open the reference oracle themselves instead of taking the
# `oracle` fixture, so they need the same guard: no oracle, no run. The
# file is not in the repository (sha256-locked, generated by
# scripts/generate_oracle.py).
from tests.data_deps import SPHERICAL_ORACLE, need, requires

pytestmark = requires(SPHERICAL_ORACLE)


PROJECT_ROOT = Path(__file__).resolve().parents[2]


def _setup():
    from backend.spherical_gpu.pipeline.detector import DetectorGeometry
    from backend.spherical_gpu.pipeline.indexer import Tier1Indexer
    from backend.spherical_gpu.pipeline.sht_io import read_sht_master
    from backend.spherical_gpu.pipeline.preprocessing import gausbckg, nregions

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    oracle_path = PROJECT_ROOT / "tests/test_spherical_gpu/data/reference_oracle.h5"
    with h5py.File(oracle_path, "r") as f:
        meta = json.loads(f.attrs["meta_json"])
        sht_bytes = bytes(f["embedded_sht_bytes"][()])
    h5oina_path = need(PROJECT_ROOT / meta["h5oina_source"])
    with h5py.File(h5oina_path, "r") as f:
        pattern_0 = f["1/EBSD/Data/Processed Patterns"][0].astype(np.float32)
    tmp = tempfile.NamedTemporaryFile(suffix=".sht", delete=False)
    tmp.write(sht_bytes); tmp.close()
    detector_params = {k: meta[k] for k in (
        "n_rows", "n_cols", "pat_width", "pat_height", "pixel_size",
        "tilt", "binning", "step_x", "step_y", "pc_x", "pc_y", "pc_z", "vendor",
    )}
    geom = DetectorGeometry.from_params(detector_params, device=device)
    master = read_sht_master(tmp.name, device=device)
    indexer = Tier1Indexer(geom, master, device, bandwidth=meta["bandwidth"])

    pat_t = torch.from_numpy(pattern_0[None, :, :]).to(device).float()
    prep = nregions(gausbckg(pat_t), n=10)
    return device, indexer, prep


def _scipy_dct_resize(im_2d_np: np.ndarray, h_out: int, w_out: int) -> np.ndarray:
    """Mimic EMSphInx Image::Rescaler.scale(): forward DCT2D on input,
    truncate or zero-pad to (h_out, w_out), inverse DCT2D.

    EMSphInx uses fft::DCT2D (real-valued, type II / III pair) — scipy.fft.dct
    type II / III is the same family. Use scipy.fft.dctn / idctn with norm='ortho'.
    """
    from scipy.fft import dctn, idctn

    H, W = im_2d_np.shape
    # forward orthonormal DCT
    F_dct = dctn(im_2d_np, type=2, norm='ortho')
    # truncate (or pad with zeros) to target shape
    F_trunc = np.zeros((h_out, w_out), dtype=F_dct.dtype)
    h_min = min(H, h_out)
    w_min = min(W, w_out)
    F_trunc[:h_min, :w_min] = F_dct[:h_min, :w_min]
    # scale factor for area change (DCT-orthonormal preserves L2 norm
    # but rescaling resamples the function; keep amplitude proportional).
    out = idctn(F_trunc, type=2, norm='ortho') * np.sqrt(
        (h_out * w_out) / (H * W)
    )
    return out


def _eval_at_gl_cells(pat_2d_np: np.ndarray, indexer, device) -> np.ndarray:
    """Sample the (already rescaled) pattern at GL inside-cells. Returns
    a (dim, dim) sphere-image (north hemi only, south=0)."""
    dim = indexer._gl_dim
    pat_t = torch.from_numpy(pat_2d_np[None, None, :, :]).to(device).float()

    omega   = indexer._dp_omega.to(device)
    gxy     = indexer._dp_grid_xy.to(device)
    s_gxy   = indexer._dp_south_grid_xy.to(device)
    s_omega = indexer._dp_south_omega.to(device)
    omega_sum = (omega.sum() + s_omega.sum()).clamp_min(1e-12)
    inside_flat = indexer._dp_inside_flat.cpu().numpy()

    grid_4d = gxy.unsqueeze(0).unsqueeze(0).expand(1, 1, -1, -1)
    sampled = F.grid_sample(
        pat_t, grid_4d, mode="bilinear",
        padding_mode="zeros", align_corners=False,
    ).squeeze(1).squeeze(1)

    if s_gxy.shape[0] > 0:
        grid_s = s_gxy.unsqueeze(0).unsqueeze(0).expand(1, 1, -1, -1)
        sampled_s = F.grid_sample(
            pat_t, grid_s, mode="bilinear",
            padding_mode="zeros", align_corners=False,
        ).squeeze(1).squeeze(1)
    else:
        sampled_s = torch.empty(1, 0, dtype=sampled.dtype, device=device)

    n_term = (sampled   * omega.unsqueeze(0)  ).sum(dim=1, keepdim=True)
    s_term = (sampled_s * s_omega.unsqueeze(0)).sum(dim=1, keepdim=True)
    mu = (n_term + s_term) / omega_sum
    res_n = sampled   - mu
    res_s = sampled_s - mu
    v_n = (res_n ** 2 * omega.unsqueeze(0)  ).sum(dim=1, keepdim=True)
    v_s = (res_s ** 2 * s_omega.unsqueeze(0)).sum(dim=1, keepdim=True)
    var = (v_n + v_s) / omega_sum
    std = var.sqrt().clamp_min(1e-6)
    f_norm = (res_n / std).cpu().numpy()[0]
    f_norm_s = (res_s / std).cpu().numpy()[0]

    sph = np.zeros((dim, dim), dtype=np.float64)
    sph_flat = sph.reshape(-1)
    sph_flat[inside_flat] = f_norm

    south_ring_inside = indexer._gl_south_ring_inside
    ring_cell_flat = indexer._gl_ring_cell_flat
    south_idx_ptr = 0
    for ar_idx in range(len(ring_cell_flat)):
        s_ins = south_ring_inside[ar_idx].cpu().numpy().astype(bool)
        n_inside = int(s_ins.sum())
        if n_inside == 0:
            continue
        ring_flat = ring_cell_flat[ar_idx].cpu().numpy().astype(np.int64)
        vals = f_norm_s[south_idx_ptr : south_idx_ptr + n_inside]
        south_idx_ptr += n_inside
        target_idx = ring_flat[s_ins]
        np.add.at(sph_flat, target_idx, vals)

    return sph


def test_rescale_methods():
    device, indexer, prep = _setup()
    H, W = prep.shape[1:]
    scale = indexer._rescale_factor
    w_out = max(1, round(W * scale))
    h_out = max(1, round(H * scale))
    pat_4d = prep.unsqueeze(1).float()
    print(f"\nFull-res pattern: {H}x{W}, target rescale: {h_out}x{w_out}, scale={scale:.4f}")

    # Load EMSphInx ground truth
    dump = json.load(open(PROJECT_ROOT / "tasks/dumptopk_pixel0.json"))
    grid_dim = dump["grid_dim"]
    em_north = np.array(dump["sphere_flat"])[:grid_dim * grid_dim].reshape(grid_dim, grid_dim)

    candidates = {
        "1_avg_pool":     lambda p: F.adaptive_avg_pool2d(p, (h_out, w_out)),
        "2_interp_area":  lambda p: F.interpolate(p, (h_out, w_out), mode='area'),
        "3_bilinear_aa":  lambda p: F.interpolate(p, (h_out, w_out), mode='bilinear', align_corners=False, antialias=True),
        "4_bicubic_aa":   lambda p: F.interpolate(p, (h_out, w_out), mode='bicubic', align_corners=False, antialias=True),
        "5_no_downsample": lambda p: p,
        "6_dct_resize":   None,  # special-case below
    }

    print(f"\n{'method':<20} {'pearson_r':>10} {'std_ratio':>10} {'mean_abs_diff':>15}")
    print("-" * 60)
    for name, fn in candidates.items():
        if name == "6_dct_resize":
            pat_np = prep.cpu().numpy()[0]
            res_np = _scipy_dct_resize(pat_np, h_out, w_out)
        else:
            with torch.no_grad():
                rescaled = fn(pat_4d.float())
            res_np = rescaled.cpu().numpy()[0, 0]
        sph_ours = _eval_at_gl_cells(res_np, indexer, device)

        common = (em_north != 0) & (sph_ours != 0)
        if common.sum() < 10:
            print(f"{name:<20} <too few common cells>")
            continue
        em_v = em_north[common]
        ours_v = sph_ours[common]
        r = float(np.corrcoef(em_v, ours_v)[0, 1])
        std_ratio = ours_v.std() / em_v.std() if em_v.std() > 0 else 0
        mean_abs_diff = float(np.abs(em_v - ours_v).mean())
        print(f"{name:<20} {r:>10.4f} {std_ratio:>10.4f} {mean_abs_diff:>15.4f}")
