"""Iter-14 beta-axis convention probe.

Goal: For a known target rotation, find the (a, b, c) in cc-volume that
gives the LOWEST cubic-m-3m disorientation. Then compare that to the
predicted (a, b, c) derived under various beta-scaling assumptions:

    Hypothesis A: beta = b * 2pi / (2L-1)              [current decoder]
    Hypothesis B: beta = b * pi / (2L-1)               [half range]
    Hypothesis C: beta = (2L-1 - b) * 2pi / (2L-1)     [flipped]
    Hypothesis D: beta = (2L-1 - b) * pi / (2L-1)      [flipped + half]
    Hypothesis E: read from peak inside cc volume

Print the WHOLE cc cube's local maxima around the target's predicted
position under each hypothesis, including the cc value at each. Whichever
hypothesis lights up an actual peak in the cc volume is the correct
convention.
"""
from __future__ import annotations

import json
import math
import sys
import tempfile
from pathlib import Path

import h5py
import numpy as np
import torch

# These probes open the reference oracle themselves instead of taking the
# `oracle` fixture, so they need the same guard: no oracle, no run. The
# file is not in the repository (sha256-locked, generated by
# scripts/generate_oracle.py).
from tests.data_deps import SPHERICAL_ORACLE, requires

pytestmark = requires(SPHERICAL_ORACLE)


PROJECT_ROOT = Path(__file__).resolve().parents[2]


def _diso_deg_zxz(target_zxz_deg, candidate_zxz_deg):
    from orix.quaternion import Misorientation, Rotation
    from orix.quaternion.symmetry import _groups
    sym = next(g for g in _groups if g.name == "m-3m")
    ra = Rotation.from_euler(np.deg2rad(np.atleast_2d(candidate_zxz_deg)))
    rb = Rotation.from_euler(np.deg2rad(np.atleast_2d(target_zxz_deg)))
    miso = Misorientation((ra * (~rb)).data, symmetry=(sym, sym))
    miso = miso.map_into_symmetry_reduced_zone()
    return float(np.rad2deg(miso.angle)[0])


def test_beta_axis_convention():
    from backend.spherical_gpu.pipeline.detector import DetectorGeometry
    from backend.spherical_gpu.pipeline.indexer import Tier1Indexer
    from backend.spherical_gpu.pipeline.sht_io import read_sht_master
    from backend.spherical_gpu.pipeline.preprocessing import gausbckg, nregions
    from backend.spherical_gpu._math.sht_cc import rs2cc_
    from tests.test_spherical_gpu._synthetic import synthetic_pattern_from_master

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    oracle_path = PROJECT_ROOT / "tests/test_spherical_gpu/data/reference_oracle.h5"
    with h5py.File(oracle_path, "r") as f:
        meta = json.loads(f.attrs["meta_json"])
        sht_bytes = bytes(f["embedded_sht_bytes"][()])
    tmp = tempfile.NamedTemporaryFile(suffix=".sht", delete=False)
    tmp.write(sht_bytes); tmp.close()

    detector_params = {k: meta[k] for k in (
        "n_rows", "n_cols", "pat_width", "pat_height", "pixel_size",
        "tilt", "binning", "step_x", "step_y", "pc_x", "pc_y", "pc_z", "vendor",
    )}
    geom = DetectorGeometry.from_params(detector_params, device=device)
    master = read_sht_master(tmp.name, device=device)
    indexer = Tier1Indexer(geom, master, device, bandwidth=meta["bandwidth"])
    L = indexer.bandwidth
    size = 2 * L - 1

    target_zxz_deg = (0.0, 30.0, 0.0)   # X30 — fails in our pipeline at 49°
    print(f"\nTarget: ZXZ {target_zxz_deg}°")

    target_zxz_rad = tuple(math.radians(x) for x in target_zxz_deg)
    synth = synthetic_pattern_from_master(
        master=master, geom=geom,
        euler_zxz=target_zxz_rad,
        flip_y=getattr(indexer, "flip_y", True),
    )
    pat_t = synth.pattern.unsqueeze(0)
    prep = nregions(gausbckg(pat_t), n=10)
    pattern_coefs = indexer._direct_sht_coefs(prep)
    cc = rs2cc_(L, pattern_coefs, indexer._master_coefs, indexer._wigner_table)
    rDen = indexer._rDen_vol.to(device)
    nc_vol = (cc.real.float() * rDen)[0].cpu().numpy()  # (size, size, size)

    # Find ABSOLUTE argmax
    flat = nc_vol.reshape(-1).argmax()
    a_abs = flat // (size * size)
    rem = flat % (size * size)
    b_abs = rem // size
    c_abs = rem % size
    print(f"Absolute peak: (a, b, c) = ({a_abs}, {b_abs}, {c_abs}), "
          f"cc = {nc_vol[a_abs, b_abs, c_abs]:.6f}")

    # For each candidate decode hypothesis, scan the cc volume and find
    # the (a, b, c) bin whose decoded ZXZ Euler gives the SMALLEST
    # disorientation from target. That's the bin most consistent with the target.
    scale = 2 * math.pi / size
    half_pi = math.pi / 2
    off = L - 1
    two_pi = 2 * math.pi

    def decode_zxz(a, b, c, beta_scale_factor=1.0, beta_flip=False):
        """Decode (a, b, c) -> ZXZ Bunge in degrees.

        beta_scale_factor: 1.0 = beta has same scale as α/γ; 0.5 = half scale.
        beta_flip: True = beta = ((size - b) mod size) * scale * factor.
        """
        alpha = ((a - off + size) % size) * scale
        gamma = ((off - c + size) % size) * scale
        if beta_flip:
            beta_idx = ((size - b) % size)
        else:
            beta_idx = b
        beta = beta_idx * scale * beta_scale_factor

        phi1 = (alpha + half_pi) % two_pi
        phi2 = (gamma - half_pi) % two_pi
        phi1 = (phi1 + 3.0 * half_pi) % two_pi
        return (math.degrees(phi1), math.degrees(beta), math.degrees(phi2))

    # Skip the brute-force min-diso scan (too slow); just show the top-10 peaks.
    print("\n=== Top-15 brightest cc bins, decoded under various beta conventions ===")
    flat_top = np.argsort(-nc_vol.reshape(-1))[:15]
    print(f"{'(a,b,c)':<14} {'cc':>8} | {'A:beta=2pi/sz':<14} {'A_diso':>7} | "
          f"{'B:beta=pi/sz':<14} {'B_diso':>7} | {'C:flip 2pi':<14} {'C_diso':>7} | "
          f"{'D:flip pi':<14} {'D_diso':>7}")
    for fi in flat_top:
        a = int(fi // (size * size)); rem = int(fi % (size * size))
        b = rem // size; c = rem % size
        v = float(nc_vol[a, b, c])
        za, zb, zc = decode_zxz(a, b, c, 1.0, False)
        zaa, zba, zca = decode_zxz(a, b, c, 0.5, False)
        zac, zbc, zcc = decode_zxz(a, b, c, 1.0, True)
        zad, zbd, zcd = decode_zxz(a, b, c, 0.5, True)
        dA = _diso_deg_zxz(target_zxz_deg, (za, zb, zc))
        dB = _diso_deg_zxz(target_zxz_deg, (zaa, zba, zca))
        dC = _diso_deg_zxz(target_zxz_deg, (zac, zbc, zcc))
        dD = _diso_deg_zxz(target_zxz_deg, (zad, zbd, zcd))
        print(
            f"({a:3d},{b:3d},{c:3d})  {v:7.3f} | "
            f"({za:5.0f},{zb:5.0f},{zc:5.0f}) {dA:6.1f} | "
            f"({zaa:5.0f},{zba:5.0f},{zca:5.0f}) {dB:6.1f} | "
            f"({zac:5.0f},{zbc:5.0f},{zcc:5.0f}) {dC:6.1f} | "
            f"({zad:5.0f},{zbd:5.0f},{zcd:5.0f}) {dD:6.1f}"
        )

