"""Iter-15: feed EMSphInx's sphere image through the NEW emsphinx_cc_kernel
(sympy-validated table + EMSphInx-formula). Compare disorientation vs the
OLD rs2cc_ kernel for the same 9 pixels.

If the new kernel gives substantially lower disorientation (<5 deg for most
pixels), we've found the right fix. If not, the bug lives elsewhere.

Test L is REDUCED to 10 (vs production 68) for speed — the slow reference
kernel is O(L^4) Python loops. Comparing with the same L on both sides is
fair as long as the bandwidth is enough to discriminate orientation
(rough bin = 360 / (2L-1) = 19 deg at L=10, plenty for top-K analysis but
peaks may be coarser).

Run: ~10 minutes on CPU for 9 pixels.
"""
from __future__ import annotations

import json
import math
import tempfile
from pathlib import Path

import h5py
import numpy as np
import torch

# These probes open the reference oracle themselves instead of taking the
# `oracle` fixture, so they need the same guard: no oracle, no run. The
# file is not in the repository (sha256-locked, generated by
# scripts/generate_oracle.py).
from tests.data_deps import SPHERICAL_ORACLE, requires

pytestmark = requires(SPHERICAL_ORACLE)


PROJECT_ROOT = Path(__file__).resolve().parents[2]


def _disorientation_deg(eu_a, eu_b):
    from orix.quaternion import Misorientation, Rotation
    from orix.quaternion.symmetry import _groups
    sym = next(g for g in _groups if g.name == "m-3m")
    r_a = Rotation.from_euler(np.atleast_2d(eu_a))
    r_b = Rotation.from_euler(np.atleast_2d(eu_b))
    miso = Misorientation((r_a * (~r_b)).data, symmetry=(sym, sym))
    miso = miso.map_into_symmetry_reduced_zone()
    return float(np.rad2deg(miso.angle)[0])


def test_emsphinx_kernel_on_real_pixel0():
    """Feed Pixel 0 EMSphInx-dumped sphere into BOTH kernels at L=10.
    Show recovered orientation under each.
    """
    from backend.spherical_gpu.pipeline.detector import DetectorGeometry
    from backend.spherical_gpu.pipeline.indexer import Tier1Indexer
    from backend.spherical_gpu.pipeline.sht_io import read_sht_master
    from backend.spherical_gpu._math.emsphinx_wigner import (
        build_wigner_d_half_pi_table,
        emsphinx_cc_kernel,
        emsphinx_cc_volume_from_spectrum,
    )

    device = torch.device("cpu")  # CPU for the slow reference kernel
    oracle_path = PROJECT_ROOT / "tests/test_spherical_gpu/data/reference_oracle.h5"
    with h5py.File(oracle_path, "r") as f:
        meta = json.loads(f.attrs["meta_json"])
        sht_bytes = bytes(f["embedded_sht_bytes"][()])
        gt_eulers = f["euler_xyz_no_refine"][:]
    tmp = tempfile.NamedTemporaryFile(suffix=".sht", delete=False)
    tmp.write(sht_bytes); tmp.close()
    detector_params = {k: meta[k] for k in (
        "n_rows", "n_cols", "pat_width", "pat_height", "pixel_size",
        "tilt", "binning", "step_x", "step_y", "pc_x", "pc_y", "pc_z", "vendor",
    )}
    geom = DetectorGeometry.from_params(detector_params, device=device)
    master = read_sht_master(tmp.name, device=device)
    indexer = Tier1Indexer(geom, master, device, bandwidth=meta["bandwidth"])

    # We use bandwidth=10 for the SHT analysis side too (faster, but coarser).
    # The master coefs are read at the storage bandwidth (384), so we truncate.
    L = 10

    # Process Pixel 0 only — keep the test manageable.
    pidx = 0
    dump_path = PROJECT_ROOT / f"tasks/dumptopk_pixel{pidx}.json"
    with open(dump_path) as f:
        dump = json.load(f)
    gd = int(dump["grid_dim"])
    em_sphere = np.array(dump["sphere_flat"])[: gd * gd].astype(np.float32)
    em_sphere_t = torch.from_numpy(em_sphere).to(device)

    # Quick SHT analyze of em_sphere using the indexer's L=68 ring tables.
    # We then truncate to L=10 for the test kernel.
    L_full = indexer.bandwidth
    coefs_full = torch.zeros(1, L_full, L_full, dtype=torch.complex64, device=device)
    ring_wy = indexer._gl_ring_wy
    ring_flat = indexer._gl_ring_cell_flat
    ring_alp = indexer._gl_ring_alp
    gl_grid = em_sphere_t.unsqueeze(0)
    for ar_idx in range(len(ring_flat)):
        ar = ar_idx + 1
        n_pts = 8 * ar
        flat_dev = ring_flat[ar_idx].to(device)
        ring_vals = gl_grid[:, flat_dev].clone().float()
        G = torch.fft.rfft(ring_vals, n=n_pts, dim=1)
        mLim = min(L_full, 4 * ar + 1)
        wy = float(ring_wy[ar_idx].item())
        alp_dev = ring_alp[ar_idx].to(device)
        for m in range(mLim):
            sign = 1.0 if m % 2 == 0 else -1.0
            factor = wy * sign * 0.5
            Gm = G[:, m]
            alp_m = alp_dev[m, m:]
            coefs_full[:, m, m:] += Gm.unsqueeze(1) * (alp_m * factor).unsqueeze(0)

    # Truncate to L=10 for the slow kernel.
    pattern_coefs = coefs_full[:, :L, :L]
    master_coefs = indexer._master_coefs[:, :L, :L]

    # Build the sympy-validated wigner table once.
    print(f"\nBuilding wigner table (L={L}) ...", flush=True)
    table = build_wigner_d_half_pi_table(L, dtype=torch.float64, device=device)
    print(f"Table shape: {table.shape}", flush=True)

    # Run the new EMSphInx-convention cc kernel on Pixel 0.
    print("Running emsphinx_cc_kernel ...", flush=True)
    spectrum = emsphinx_cc_kernel(pattern_coefs, master_coefs, table, L)
    cc_volume = emsphinx_cc_volume_from_spectrum(spectrum)
    print(f"cc volume shape: {cc_volume.shape}", flush=True)

    # Find argmax + decode.
    nc_vol = cc_volume[0]
    sl = 2 * L - 1
    flat_idx = nc_vol.reshape(-1).argmax().item()
    a = flat_idx // (sl * sl)
    rem = flat_idx % (sl * sl)
    b = rem // sl
    c = rem % sl

    # Decode (a, b, c) -> ZXZ Bunge (same formula as Tier1Indexer)
    scale = 2.0 * math.pi / sl
    off = L - 1
    half_pi = math.pi / 2.0
    two_pi = 2.0 * math.pi
    sl_f = float(sl)
    a_f = float(a); b_f = float(b); c_f = float(c)
    alpha = ((a_f - off + sl_f) % sl_f + sl_f) % sl_f * scale
    gamma = ((off - c_f + sl_f) % sl_f + sl_f) % sl_f * scale
    Phi = b_f * scale
    phi1 = (alpha + half_pi) % two_pi
    phi2 = (gamma - half_pi) % two_pi
    phi1 = (phi1 + 3.0 * half_pi) % two_pi
    rec = (phi1, Phi, phi2)
    gt = tuple(float(x) for x in gt_eulers[pidx])
    diso = _disorientation_deg(np.array(rec), np.array(gt))

    print(f"\nPixel {pidx}:")
    print(f"  GT  (deg): ({math.degrees(gt[0]):5.1f}, {math.degrees(gt[1]):5.1f}, {math.degrees(gt[2]):5.1f})")
    print(f"  Rec (deg): ({math.degrees(rec[0]):5.1f}, {math.degrees(rec[1]):5.1f}, {math.degrees(rec[2]):5.1f})")
    print(f"  cc-best-bin diso: {diso:.2f} deg")
    print(f"  cc volume (a, b, c) peak: ({a}, {b}, {c}) value={float(nc_vol[a, b, c].item()):.4f}")
