"""Iter-14 real-data cc-peak diagnostic.

Goal: Use Oracle Pixel 0 (which has WSL-EMSphInx ground-truth orientation)
to disambiguate the cc-volume decode convention.

Procedure:
1. Load Oracle Pattern Pixel 0 + its WSL-EMSphInx Bunge ZXZ Euler.
2. Run our pipeline up to nc_vol.
3. For each of the top-25 cc bins, decode under 4 hypotheses:
   A: Phi = b * 2pi/sz                              (current)
   B: Phi = b * pi/sz                               (half-range)
   C: Phi = (sz-b) * 2pi/sz                         (flipped)
   D: Phi = (sz-b) * pi/sz                          (flipped + half)
4. For each, compute m-3m disorientation vs WSL ground-truth.
5. Lowest diso wins.

If hypothesis A wins: decoder is fine, bug is upstream.
If B/C/D wins: decoder bug, fix scale_factor or flip in indexer.py:381.
"""
from __future__ import annotations

import json
import math
import sys
import tempfile
from pathlib import Path

import h5py
import numpy as np
import pytest
import torch

# These probes open the reference oracle themselves instead of taking the
# `oracle` fixture, so they need the same guard: no oracle, no run. The
# file is not in the repository (sha256-locked, generated by
# scripts/generate_oracle.py).
from tests.data_deps import SPHERICAL_ORACLE, need, requires

pytestmark = requires(SPHERICAL_ORACLE)


PROJECT_ROOT = Path(__file__).resolve().parents[2]


def _diso_deg_zxz(target_zxz_rad, candidate_zxz_deg):
    from orix.quaternion import Misorientation, Rotation
    from orix.quaternion.symmetry import _groups
    sym = next(g for g in _groups if g.name == "m-3m")
    target_deg = [math.degrees(x) for x in target_zxz_rad]
    ra = Rotation.from_euler(np.deg2rad(np.atleast_2d(candidate_zxz_deg)))
    rb = Rotation.from_euler(np.deg2rad(np.atleast_2d(target_deg)))
    miso = Misorientation((ra * (~rb)).data, symmetry=(sym, sym))
    miso = miso.map_into_symmetry_reduced_zone()
    return float(np.rad2deg(miso.angle)[0])


def test_realdata_peak_decode_hypotheses():
    from backend.spherical_gpu.pipeline.detector import DetectorGeometry
    from backend.spherical_gpu.pipeline.indexer import Tier1Indexer
    from backend.spherical_gpu.pipeline.sht_io import read_sht_master
    from backend.spherical_gpu.pipeline.preprocessing import gausbckg, nregions
    from backend.spherical_gpu._math.sht_cc import rs2cc_

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    oracle_path = PROJECT_ROOT / "tests/test_spherical_gpu/data/reference_oracle.h5"
    with h5py.File(oracle_path, "r") as f:
        meta = json.loads(f.attrs["meta_json"])
        sht_bytes = bytes(f["embedded_sht_bytes"][()])
        # WSL-EMSphInx ground-truth Bunge ZXZ Euler (radians) for pixel 0
        gt_eulers = f["euler_xyz_no_refine"][0]
    h5oina_path = need(PROJECT_ROOT / meta["h5oina_source"])
    with h5py.File(h5oina_path, "r") as f:
        pattern_0 = f["1/EBSD/Data/Processed Patterns"][0].astype(np.float32)
    target_zxz_rad = tuple(float(x) for x in gt_eulers)
    print(f"\n--- Real-data peak-dump diagnostic ---")
    print(f"Oracle Pixel 0 ground-truth ZXZ (deg): "
          f"({math.degrees(target_zxz_rad[0]):.2f}, "
          f"{math.degrees(target_zxz_rad[1]):.2f}, "
          f"{math.degrees(target_zxz_rad[2]):.2f})")

    tmp = tempfile.NamedTemporaryFile(suffix=".sht", delete=False)
    tmp.write(sht_bytes); tmp.close()

    detector_params = {k: meta[k] for k in (
        "n_rows", "n_cols", "pat_width", "pat_height", "pixel_size",
        "tilt", "binning", "step_x", "step_y", "pc_x", "pc_y", "pc_z", "vendor",
    )}
    geom = DetectorGeometry.from_params(detector_params, device=device)
    master = read_sht_master(tmp.name, device=device)
    indexer = Tier1Indexer(geom, master, device, bandwidth=meta["bandwidth"])
    L = indexer.bandwidth
    size = 2 * L - 1
    off = L - 1
    scale = 2 * math.pi / size
    half_pi = math.pi / 2
    two_pi = 2 * math.pi

    # Run pipeline up to nc_vol on the real pattern
    pat_t = torch.from_numpy(pattern_0[None, :, :]).to(device).float()
    prep = nregions(gausbckg(pat_t), n=10)
    pattern_coefs = indexer._direct_sht_coefs(prep)
    cc = rs2cc_(L, pattern_coefs, indexer._master_coefs, indexer._wigner_table)
    rDen = indexer._rDen_vol.to(device)
    nc_vol = (cc.real.float() * rDen)[0].cpu().numpy()

    flat = nc_vol.reshape(-1).argmax()
    a_abs = flat // (size * size)
    rem = flat % (size * size)
    b_abs = rem // size
    c_abs = rem % size
    print(f"Absolute peak: (a, b, c) = ({a_abs}, {b_abs}, {c_abs}), "
          f"cc = {nc_vol[a_abs, b_abs, c_abs]:.4f}")

    def decode(a, b, c, beta_scale_factor=1.0, beta_flip=False):
        """Decode (a, b, c) -> (phi1, Phi, phi2) ZXZ Bunge in degrees."""
        alpha = ((a - off + size) % size) * scale
        gamma = ((off - c + size) % size) * scale
        if beta_flip:
            beta_idx = ((size - b) % size)
        else:
            beta_idx = b
        beta = beta_idx * scale * beta_scale_factor
        phi1 = (alpha + half_pi) % two_pi
        phi2 = (gamma - half_pi) % two_pi
        phi1 = (phi1 + 3.0 * half_pi) % two_pi
        return (math.degrees(phi1), math.degrees(beta), math.degrees(phi2))

    # Top-25 cc bins
    flat_top = np.argsort(-nc_vol.reshape(-1))[:25]
    print(f"\n=== Top-25 cc-bins, decoded under 4 hypotheses ===")
    print(f"{'(a,b,c)':<14} {'cc':>7} | "
          f"{'A:full+direct':<18} {'A_dis':>6} | "
          f"{'B:half+direct':<18} {'B_dis':>6} | "
          f"{'C:full+flip':<18} {'C_dis':>6} | "
          f"{'D:half+flip':<18} {'D_dis':>6}")

    best_per_hyp = {"A": (999, None), "B": (999, None), "C": (999, None), "D": (999, None)}

    for fi in flat_top:
        a = int(fi // (size * size))
        rem = int(fi % (size * size))
        b = rem // size; c = rem % size
        v = float(nc_vol[a, b, c])

        zA = decode(a, b, c, 1.0, False)
        zB = decode(a, b, c, 0.5, False)
        zC = decode(a, b, c, 1.0, True)
        zD = decode(a, b, c, 0.5, True)

        dA = _diso_deg_zxz(target_zxz_rad, zA)
        dB = _diso_deg_zxz(target_zxz_rad, zB)
        dC = _diso_deg_zxz(target_zxz_rad, zC)
        dD = _diso_deg_zxz(target_zxz_rad, zD)

        for name, d in [("A", dA), ("B", dB), ("C", dC), ("D", dD)]:
            if d < best_per_hyp[name][0]:
                best_per_hyp[name] = (d, (a, b, c))

        print(
            f"({a:3d},{b:3d},{c:3d})  {v:6.3f} | "
            f"({zA[0]:5.0f},{zA[1]:5.0f},{zA[2]:5.0f}) {dA:5.1f} | "
            f"({zB[0]:5.0f},{zB[1]:5.0f},{zB[2]:5.0f}) {dB:5.1f} | "
            f"({zC[0]:5.0f},{zC[1]:5.0f},{zC[2]:5.0f}) {dC:5.1f} | "
            f"({zD[0]:5.0f},{zD[1]:5.0f},{zD[2]:5.0f}) {dD:5.1f}"
        )

    print("\n=== Best disorientation per hypothesis (across top-25) ===")
    for name, (d, cell) in sorted(best_per_hyp.items(), key=lambda x: x[1][0]):
        label = {"A": "full+direct (current)", "B": "half+direct",
                 "C": "full+flip",            "D": "half+flip"}[name]
        print(f"  Hypothesis {name} ({label:<25}): best_diso = {d:5.2f} deg  cell={cell}")

    print("\nInterpretation:")
    print("  Best diso < 5 deg under hypothesis X => the decode formula needs")
    print("  to be changed accordingly. Bug is in indexer.py:378-385 (decode).")
    print("  All hypotheses > 10 deg => bug is upstream of decode.")
