"""Iter-14+1: Isolate the preprocessing contribution to the per-cell residual.

Run sphere-compare 4 times with different preprocessing flavors:
  A: gausbckg + nregions(n=10)        — current
  B: nregions(n=10) only              — no Gaussian background
  C: gausbckg only                    — no AHE
  D: raw pattern                       — no preprocessing

Whichever gives the highest pearson r identifies the preprocessing
mismatch with EMSphInx.
"""
from __future__ import annotations

import json
import tempfile
from pathlib import Path

import h5py
import numpy as np
import torch
import torch.nn.functional as F

# These probes open the reference oracle themselves instead of taking the
# `oracle` fixture, so they need the same guard: no oracle, no run. The
# file is not in the repository (sha256-locked, generated by
# scripts/generate_oracle.py).
from tests.data_deps import SPHERICAL_ORACLE, need, requires

pytestmark = requires(SPHERICAL_ORACLE)


PROJECT_ROOT = Path(__file__).resolve().parents[2]


def _eval_sphere(prep, indexer, device):
    """Compute our stage-1 sphere image given a preprocessed pattern."""
    pat_4d = prep.unsqueeze(1).float()
    H, W = prep.shape[1:]
    scale = indexer._rescale_factor
    w_out = max(1, round(W * scale))
    h_out = max(1, round(H * scale))
    if w_out < W or h_out < H:
        pat_4d = F.interpolate(
            pat_4d, (h_out, w_out),
            mode="bicubic", align_corners=False, antialias=True,
        )

    omega   = indexer._dp_omega.to(device)
    gxy     = indexer._dp_grid_xy.to(device)
    s_gxy   = indexer._dp_south_grid_xy.to(device)
    s_omega = indexer._dp_south_omega.to(device)
    omega_sum = (omega.sum() + s_omega.sum()).clamp_min(1e-12)
    inside_flat = indexer._dp_inside_flat.cpu().numpy()

    grid_4d = gxy.unsqueeze(0).unsqueeze(0).expand(1, 1, -1, -1)
    sampled = F.grid_sample(
        pat_4d, grid_4d, mode="bilinear",
        padding_mode="zeros", align_corners=True,
    ).squeeze(1).squeeze(1)

    if s_gxy.shape[0] > 0:
        grid_s = s_gxy.unsqueeze(0).unsqueeze(0).expand(1, 1, -1, -1)
        sampled_s = F.grid_sample(
            pat_4d, grid_s, mode="bilinear",
            padding_mode="zeros", align_corners=True,
        ).squeeze(1).squeeze(1)
    else:
        sampled_s = torch.empty(1, 0, dtype=sampled.dtype, device=device)

    n_term = (sampled   * omega.unsqueeze(0)  ).sum(dim=1, keepdim=True)
    s_term = (sampled_s * s_omega.unsqueeze(0)).sum(dim=1, keepdim=True)
    mu = (n_term + s_term) / omega_sum
    res_n = sampled   - mu
    res_s = sampled_s - mu
    v_n = (res_n ** 2 * omega.unsqueeze(0)  ).sum(dim=1, keepdim=True)
    v_s = (res_s ** 2 * s_omega.unsqueeze(0)).sum(dim=1, keepdim=True)
    var = (v_n + v_s) / omega_sum
    std = var.sqrt().clamp_min(1e-6)
    f_norm = (res_n / std).cpu().numpy()[0]
    f_norm_s = (res_s / std).cpu().numpy()[0]

    dim = indexer._gl_dim
    sph = np.zeros((dim, dim), dtype=np.float64)
    sph_flat = sph.reshape(-1)
    sph_flat[inside_flat] = f_norm

    south_ring_inside = indexer._gl_south_ring_inside
    ring_cell_flat = indexer._gl_ring_cell_flat
    south_idx_ptr = 0
    for ar_idx in range(len(ring_cell_flat)):
        s_ins = south_ring_inside[ar_idx].cpu().numpy().astype(bool)
        n_inside = int(s_ins.sum())
        if n_inside == 0:
            continue
        ring_flat_arr = ring_cell_flat[ar_idx].cpu().numpy().astype(np.int64)
        vals = f_norm_s[south_idx_ptr : south_idx_ptr + n_inside]
        south_idx_ptr += n_inside
        np.add.at(sph_flat, ring_flat_arr[s_ins], vals)

    return sph


def test_preprocessing_variants():
    from backend.spherical_gpu.pipeline.detector import DetectorGeometry
    from backend.spherical_gpu.pipeline.indexer import Tier1Indexer
    from backend.spherical_gpu.pipeline.sht_io import read_sht_master
    from backend.spherical_gpu.pipeline.preprocessing import gausbckg, nregions

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    oracle_path = PROJECT_ROOT / "tests/test_spherical_gpu/data/reference_oracle.h5"
    with h5py.File(oracle_path, "r") as f:
        meta = json.loads(f.attrs["meta_json"])
        sht_bytes = bytes(f["embedded_sht_bytes"][()])
    h5oina_path = need(PROJECT_ROOT / meta["h5oina_source"])
    with h5py.File(h5oina_path, "r") as f:
        pat = f["1/EBSD/Data/Processed Patterns"][0].astype(np.float32)
    tmp = tempfile.NamedTemporaryFile(suffix=".sht", delete=False)
    tmp.write(sht_bytes); tmp.close()
    detector_params = {k: meta[k] for k in (
        "n_rows", "n_cols", "pat_width", "pat_height", "pixel_size",
        "tilt", "binning", "step_x", "step_y", "pc_x", "pc_y", "pc_z", "vendor",
    )}
    geom = DetectorGeometry.from_params(detector_params, device=device)
    master = read_sht_master(tmp.name, device=device)
    indexer = Tier1Indexer(geom, master, device, bandwidth=meta["bandwidth"])

    # Load EMSphInx ground truth
    dump_path = PROJECT_ROOT / "tasks/dumptopk_pixel0.json"
    with open(dump_path) as f:
        dump = json.load(f)
    grid_dim = int(dump["grid_dim"])
    em_north = np.array(dump["sphere_flat"])[: grid_dim * grid_dim].reshape(grid_dim, grid_dim)

    pat_t = torch.from_numpy(pat[None, :, :]).to(device).float()

    variants = {
        "A: gausbckg + nregions(10)": nregions(gausbckg(pat_t), n=10),
        "B: nregions(10) only       ": nregions(pat_t, n=10),
        "C: gausbckg only            ": gausbckg(pat_t),
        "D: raw pattern              ": pat_t,
        "E: nregions(8)              ": nregions(gausbckg(pat_t), n=8),
        "F: nregions(12)             ": nregions(gausbckg(pat_t), n=12),
        "G: nregions(15)             ": nregions(gausbckg(pat_t), n=15),
    }

    print()
    print(f"{'variant':<32} {'r':>8} {'std_ratio':>10} {'mean_abs_diff':>14}")
    print("-" * 70)
    for name, prep in variants.items():
        sph = _eval_sphere(prep, indexer, device)
        common = (em_north != 0) & (sph != 0)
        em_v = em_north[common]
        ours_v = sph[common]
        if ours_v.std() == 0 or em_v.std() == 0:
            r = float("nan")
        else:
            r = float(np.corrcoef(em_v, ours_v)[0, 1])
        std_ratio = ours_v.std() / em_v.std() if em_v.std() > 0 else 0
        mean_abs = float(np.abs(em_v - ours_v).mean())
        print(f"{name:<32} {r:>8.4f} {std_ratio:>10.4f} {mean_abs:>14.4f}")
