"""Iter-14 axis-convention probe.

Hypothesis: rs2cc_ output's β-axis covers [0, 2π) but our decoder treats
all three axes as [0, 2π). For the standard SO(3) FFT, β should be in
[0, π) — half the range of α and γ.

Concrete check: feed identity (master==pattern) into rs2cc_. The peak MUST
be at a single, unambiguous (a, b, c). Whatever (a, b, c) is observed
defines the β axis convention.
"""
from __future__ import annotations

import json
import math
import tempfile
from pathlib import Path

import h5py
import torch

# These probes open the reference oracle themselves instead of taking the
# `oracle` fixture, so they need the same guard: no oracle, no run. The
# file is not in the repository (sha256-locked, generated by
# scripts/generate_oracle.py).
from tests.data_deps import SPHERICAL_ORACLE, requires

pytestmark = requires(SPHERICAL_ORACLE)


def test_identity_peak_position():
    PROJECT_ROOT = Path(__file__).resolve().parents[2]
    from backend.spherical_gpu.pipeline.detector import DetectorGeometry
    from backend.spherical_gpu.pipeline.indexer import Tier1Indexer
    from backend.spherical_gpu.pipeline.sht_io import read_sht_master
    from backend.spherical_gpu._math.sht_cc import rs2cc_

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    oracle_path = PROJECT_ROOT / "tests/test_spherical_gpu/data/reference_oracle.h5"
    with h5py.File(oracle_path, "r") as f:
        meta = json.loads(f.attrs["meta_json"])
        sht_bytes = bytes(f["embedded_sht_bytes"][()])
    tmp = tempfile.NamedTemporaryFile(suffix=".sht", delete=False)
    tmp.write(sht_bytes); tmp.close()

    detector_params = {k: meta[k] for k in (
        "n_rows", "n_cols", "pat_width", "pat_height", "pixel_size",
        "tilt", "binning", "step_x", "step_y", "pc_x", "pc_y", "pc_z", "vendor",
    )}
    geom = DetectorGeometry.from_params(detector_params, device=device)
    master = read_sht_master(tmp.name, device=device)
    indexer = Tier1Indexer(geom, master, device, bandwidth=meta["bandwidth"])
    L = indexer.bandwidth
    size = 2 * L - 1

    # Feed master coefs as both pattern AND master into rs2cc_.
    # Identity rotation should produce the maximum cc.
    M = indexer._master_coefs.clone()  # (1, L, L) complex
    cc = rs2cc_(L, M, M, indexer._wigner_table)  # (1, size, size, size)
    cc_real = cc[0].real

    flat = cc_real.reshape(-1).argmax().item()
    a = flat // (size * size)
    rem = flat % (size * size)
    b = rem // size
    c = rem % size
    peak_value = float(cc_real[a, b, c].item())
    expected_identity_a = L - 1   # = 67 — comment in indexer.py says (off, 0, off)
    expected_identity_b = 0
    expected_identity_c = L - 1

    print(
        f"\nIdentity master->master peak: (a, b, c) = ({a}, {b}, {c}), "
        f"value = {peak_value:.6f}"
    )
    print(
        f"Comment in indexer.py says identity is at (off, 0, off) = "
        f"({expected_identity_a}, {expected_identity_b}, {expected_identity_c})"
    )
    print(f"size = {size}, L = {L}")

    # Print top-5 peaks
    flat_top5 = torch.topk(cc_real.flatten(), 5)
    print("Top-5 peaks (cc_value, a, b, c):")
    for v, i in zip(flat_top5.values.cpu().numpy(), flat_top5.indices.cpu().numpy()):
        ai = i // (size * size); ri = i % (size * size)
        bi = ri // size; ci = ri % size
        print(f"  cc={float(v):.6f}  (a={int(ai)}, b={int(bi)}, c={int(ci)})")

    assert math.isfinite(peak_value), "non-finite peak"
