"""Iter-14+3: feed EMSphInx's exact sphere image (from DumpTopK) into our
cc kernel. If it indexes correctly, our cc kernel + decode + master loading
are all fine — the bug is purely in detector->sphere. If it fails, our
cc kernel itself has a bias.
"""
from __future__ import annotations

import json
import math
import tempfile
from pathlib import Path

import h5py
import numpy as np
import torch

# These probes open the reference oracle themselves instead of taking the
# `oracle` fixture, so they need the same guard: no oracle, no run. The
# file is not in the repository (sha256-locked, generated by
# scripts/generate_oracle.py).
from tests.data_deps import SPHERICAL_ORACLE, requires

pytestmark = requires(SPHERICAL_ORACLE)


PROJECT_ROOT = Path(__file__).resolve().parents[2]


def _disorientation_deg(eu_a, eu_b):
    from orix.quaternion import Misorientation, Rotation
    from orix.quaternion.symmetry import _groups
    sym = next(g for g in _groups if g.name == "m-3m")
    r_a = Rotation.from_euler(np.atleast_2d(eu_a))
    r_b = Rotation.from_euler(np.atleast_2d(eu_b))
    miso = Misorientation((r_a * (~r_b)).data, symmetry=(sym, sym))
    miso = miso.map_into_symmetry_reduced_zone()
    return float(np.rad2deg(miso.angle)[0])


def test_emsphinx_sphere_through_our_cc():
    """For each of 9 oracle pixels, take the EMSphInx-dumped sphere
    image and feed it into our SHT-analyze + cc + decode pipeline.
    Compare recovered orientation against EMSphInx's no-refine ground truth.
    """
    from backend.spherical_gpu.pipeline.detector import DetectorGeometry
    from backend.spherical_gpu.pipeline.indexer import Tier1Indexer
    from backend.spherical_gpu.pipeline.sht_io import read_sht_master
    from backend.spherical_gpu._math.sht_cc import rs2cc_

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    oracle_path = PROJECT_ROOT / "tests/test_spherical_gpu/data/reference_oracle.h5"
    with h5py.File(oracle_path, "r") as f:
        meta = json.loads(f.attrs["meta_json"])
        sht_bytes = bytes(f["embedded_sht_bytes"][()])
        gt_eulers = f["euler_xyz_no_refine"][:]
    tmp = tempfile.NamedTemporaryFile(suffix=".sht", delete=False)
    tmp.write(sht_bytes); tmp.close()
    detector_params = {k: meta[k] for k in (
        "n_rows", "n_cols", "pat_width", "pat_height", "pixel_size",
        "tilt", "binning", "step_x", "step_y", "pc_x", "pc_y", "pc_z", "vendor",
    )}
    geom = DetectorGeometry.from_params(detector_params, device=device)
    master = read_sht_master(tmp.name, device=device)
    indexer = Tier1Indexer(geom, master, device, bandwidth=meta["bandwidth"])

    L = indexer.bandwidth
    dim = indexer._gl_dim

    pixel_indices = [0, 5, 8, 9, 12, 16, 17, 40, 42]
    print()
    print(f"{'pixel':>5} {'gt_zxz_deg':<22} {'rec_zxz_deg':<22} {'diso_deg':>8}")
    print("-" * 65)

    for pidx in pixel_indices:
        dump_path = PROJECT_ROOT / f"tasks/dumptopk_pixel{pidx}.json"
        if not dump_path.exists():
            print(f"  pixel {pidx}: dump missing, skip")
            continue
        with open(dump_path) as f:
            dump = json.load(f)
        gd = int(dump["grid_dim"])
        # EMSphInx sphere image (north hemi only, gd*gd values)
        em_sphere = np.array(dump["sphere_flat"])[: gd * gd].astype(np.float32)
        em_sphere_t = torch.from_numpy(em_sphere).to(device)

        # Now: feed em_sphere to our SHT-analyze (Stage 4 of _direct_sht_coefs).
        # The Stage 4 expects gl_grid (B, dim*dim) where the values at GL inside
        # cells are the sphere image values.
        # Build gl_grid for ONE batch pattern from em_sphere.
        gl_grid = em_sphere_t.unsqueeze(0)  # (1, dim*dim)

        # Run Stage 4 ring-by-ring SHT analyze (copy from _direct_sht_coefs).
        coefs = torch.zeros(1, L, L, dtype=torch.complex64, device=device)
        ring_wy = indexer._gl_ring_wy
        ring_flat = indexer._gl_ring_cell_flat
        ring_alp = indexer._gl_ring_alp

        for ar_idx in range(len(ring_flat)):
            ar = ar_idx + 1
            n_pts = 8 * ar
            flat_dev = ring_flat[ar_idx].to(device)
            ring_vals = gl_grid[:, flat_dev].clone().float()
            G = torch.fft.rfft(ring_vals, n=n_pts, dim=1)
            mLim = min(L, 4 * ar + 1)
            wy = float(ring_wy[ar_idx].item())
            alp_dev = ring_alp[ar_idx].to(device)
            for m in range(mLim):
                sign = 1.0 if m % 2 == 0 else -1.0
                factor = wy * sign * 0.5
                Gm = G[:, m]
                alp_m = alp_dev[m, m:]
                coefs[:, m, m:] += Gm.unsqueeze(1) * (alp_m * factor).unsqueeze(0)

        # Cross-correlate with master, find peak, decode.
        cc = rs2cc_(L, coefs, indexer._master_coefs, indexer._wigner_table)
        rDen = indexer._rDen_vol.to(device)
        nc_vol = (cc.real.float() * rDen)[0]
        # iter-15A EXPERIMENT: try ALL 6 axis-permutations for the argmax
        # cell. Per the Lenthe Eq. 11 derivation, the spatial axes from
        # EMSphInx's (k_idx, n_idx, m_idx) spectrum layout become
        # (beta, alpha, gamma) NOT (alpha, beta, gamma). We test all 6
        # permutations and report the one that gives lowest m-3m diso for
        # this pixel. The permutation that wins on MOST pixels is the
        # correct convention.
        size = 2 * L - 1
        flat_idx = nc_vol.reshape(-1).argmax().item()
        a0 = flat_idx // (size * size)
        rem0 = flat_idx % (size * size)
        b0 = rem0 // size
        c0 = rem0 % size

        from itertools import permutations
        from orix.quaternion import Misorientation, Rotation as _OR
        from orix.quaternion.symmetry import _groups
        sym = next(g for g in _groups if g.name == "m-3m")
        scale = 2.0 * math.pi / size
        off = L - 1
        size_f = float(size)
        half_pi = math.pi / 2.0
        two_pi = 2.0 * math.pi
        gt = tuple(math.degrees(float(x)) for x in gt_eulers[pidx])

        best_diso = 999.0
        best_perm = None
        for perm in permutations([0, 1, 2]):
            cell = (a0, b0, c0)
            a = cell[perm.index(0)]
            b = cell[perm.index(1)]
            c = cell[perm.index(2)]
            a_f = float(a); b_f = float(b); c_f = float(c)
            alpha = ((a_f - off + size_f) % size_f + size_f) % size_f * scale
            gamma = ((off - c_f + size_f) % size_f + size_f) % size_f * scale
            Phi   = b_f * scale
            phi1  = (alpha + half_pi) % two_pi
            phi2  = (gamma - half_pi) % two_pi
            phi1  = (phi1 + 3.0 * half_pi) % two_pi
            rec = (math.degrees(phi1), math.degrees(Phi), math.degrees(phi2))
            r_a = _OR.from_euler(np.deg2rad(np.atleast_2d(rec)))
            r_b = _OR.from_euler(np.deg2rad(np.atleast_2d(gt)))
            miso = Misorientation((r_a * (~r_b)).data, symmetry=(sym, sym))
            miso = miso.map_into_symmetry_reduced_zone()
            d = float(np.rad2deg(miso.angle)[0])
            if d < best_diso:
                best_diso = d
                best_perm = perm
        print(f"  Pixel {pidx}: best perm={best_perm} diso={best_diso:.2f}")

        # Use the original (no-permute) for the main printed report
        a, b, c = a0, b0, c0

        # Decode (a, b, c) -> ZXZ Bunge
        scale = 2.0 * math.pi / size
        off = L - 1
        size_f = float(size)
        half_pi = math.pi / 2.0
        two_pi = 2.0 * math.pi
        a_f = float(a); b_f = float(b); c_f = float(c)
        alpha = ((a_f - off + size_f) % size_f + size_f) % size_f * scale
        gamma = ((off - c_f + size_f) % size_f + size_f) % size_f * scale
        Phi = b_f * scale
        phi1 = (alpha + half_pi) % two_pi
        phi2 = (gamma - half_pi) % two_pi
        phi1 = (phi1 + 3.0 * half_pi) % two_pi
        rec = (phi1, Phi, phi2)
        gt = tuple(float(x) for x in gt_eulers[pidx])
        diso = _disorientation_deg(np.array(rec), np.array(gt))

        print(
            f"{pidx:>5} ({math.degrees(gt[0]):5.1f},{math.degrees(gt[1]):5.1f},{math.degrees(gt[2]):5.1f}) "
            f"({math.degrees(rec[0]):5.1f},{math.degrees(rec[1]):5.1f},{math.degrees(rec[2]):5.1f}) "
            f"{diso:>8.2f}"
        )
