"""An add-on's works, joined to the core bibliography.

Stage 1 made a result say what produced it. This is the join: an add-on carries
its citations in its own manifest, and they are registered beside Orienta's so
the citation panel and the /Citations group of an exported .h5 treat them
identically. Nothing is written into library.json — the core bibliography stays
the core's; the entries live in a process-level registry that ``load_library()``
merges, the same shape as ``register_step``.

**Lifetime — a known property, not a bug.** Both registries this module writes
to are APPEND-ONLY for the life of the process: ``register_library_entries``
adds with ``setdefault``, and ``register_manifest_citations`` skips an analysis
key ITS OWN add-on already declared. So an add-on re-scanned after its manifest
changed keeps the declaration it had at FIRST registration, and a disabled
add-on's entries stay in the bibliography until the backend restarts. That is
harmless for rendering today — entries are only ever read through ``cid in
library`` (``routes/citations.py``, ``result_exporter._write_citations``), so a
stale one costs nothing unless a step still cites it — and it is the
conservative direction: overwriting a live declaration mid-session would change
what an already-rendered methods paragraph claims. Clearing belongs to whoever
builds re-scan (Task 7), together with the decision of what to do about results
already stamped with the old declaration.

**One key, one add-on.** The skip above is by OWNER, and that distinction is
the whole of :class:`AnalysisKeyConflict`: skipping on the key alone handed a
second add-on declaring the same key the FIRST one's citations and sentence,
under the second one's numbers.

**The test suite cannot see any of this.** ``tests/addons/conftest.py`` saves
and restores ``STEP_REGISTRY`` and ``ADDON_LIBRARY_ENTRIES`` in place around
every test, so each test starts from the pristine core state and no test ever
reaches a second process-lifetime registration. Anyone measuring the property
above has to do it outside pytest.
"""
from __future__ import annotations

import logging
from typing import Dict, List

from ..citations import render as render_mod
from ..citations.render import load_library, register_library_entries
from ..citations.steps import StepCitation, get_step, register_step
from .manifest import AddonManifest

logger = logging.getLogger(__name__)

_DOI_PREFIX = "doi:"


def _core_library_ids() -> set[str]:
    """Ids the CORE bibliography already resolves. Never fabricate over one.

    The subtraction is the whole function. ``load_library()`` MERGES
    ``ADDON_LIBRARY_ENTRIES``, so once any add-on has registered, what it
    returns is the core's bibliography plus every add-on's — and reading that
    as "the core" tells an add-on that the core resolves its own DOI.
    ``register_manifest_citations`` would then report it contributed nothing,
    and add-on B declaring the same DOI as add-on A would be told so on its
    FIRST call. The registry itself is unaffected either way (``setdefault``);
    what is affected is the list of ids this module hands back, which Tasks 7
    and 8b read as "this add-on's works".

    ``ADDON_LIBRARY_ENTRIES`` is read through the MODULE, not through a name
    bound at import: it is mutated in place (conftest.py restores it that way
    too), so a reference captured once would go stale.
    """
    try:
        library = set(load_library())
    except Exception:
        # A bibliography that cannot be loaded costs us the check, not the
        # run; the citations route already degrades the same way. The cost is
        # named: without it, a reference the core DOES resolve gets a
        # placeholder entry minted over it.
        logger.exception("could not read the core library while resolving "
                         "an add-on's references")
        return set()
    return library - set(render_mod.ADDON_LIBRARY_ENTRIES)


def _entry_for(reference: str, manifest: AddonManifest) -> dict:
    if reference.startswith(_DOI_PREFIX):
        doi = reference[len(_DOI_PREFIX):]
        # ``document`` is not in render._BIBTEX_TYPE, so this renders as
        # @misc — render.py's stated house rule for a structure we do not
        # know, and we know nothing here: Orienta resolves no DOIs at run
        # time, and a DOI can be a paper, a Zenodo deposit or a data set.
        # "article-journal" would render @article and assert a journal.
        #
        # The title names NO add-on, deliberately. One DOI is one library
        # entry, so the first add-on to declare it would otherwise put its
        # name on a work that a second add-on cites too — a false provenance
        # statement, generated by us, in text a researcher may paste into a
        # paper. The id, DOI and URL are what actually reach the work, and
        # none of them can go stale.
        return {
            "id": reference,
            "type": "document",
            "title": f"[work {doi}; title not resolved offline]",
            "DOI": doi,
            "URL": f"https://doi.org/{doi}",
        }
    # Shown, not dropped: a reference we cannot turn into an entry is a gap in
    # the add-on's bookkeeping, and hiding it would make the list look
    # complete. The add-on's name STAYS here, unlike the DOI branch above:
    # there is no id, DOI or URL that reaches anything, so naming who declared
    # the broken reference is the only actionable thing the line can carry.
    return {
        "id": reference,
        "type": "document",
        "title": f"[unresolved reference {reference!r} from {manifest.name}]",
    }


def addon_library_entries(manifest: AddonManifest) -> Dict[str, dict]:
    """CSL-JSON entries for everything this manifest asks to be cited with.

    A reference the CORE library already resolves (e.g. ``"orienta"``) is left
    alone — citing it means that entry, not a second copy of it.
    """
    known = _core_library_ids()
    entries: Dict[str, dict] = {}
    references: List[str] = []
    if manifest.doi:
        references.append(f"{_DOI_PREFIX}{manifest.doi}")
    for analysis in manifest.analyses:
        references.extend(analysis.citations)
    for reference in references:
        if reference in known or reference in entries:
            continue
        entries[reference] = _entry_for(reference, manifest)
    return entries


class AnalysisKeyConflict(Exception):
    """Two different add-ons declare one analysis key. Names both."""


def _owner_description(step) -> str:
    return (f"the add-on {step.owner!r}" if step.owner
            else "Orienta itself, as a core pipeline step")


def _owner_is_installed(owner: str) -> bool:
    """Is an add-on of that name still on this machine?

    Asked only once a conflict has already been found, so the cost -- a full
    manifest scan, measured at 37 ms for five add-ons -- is paid on the
    refusal path and nowhere else.

    A scan and not a remembered set: the registries here are append-only for
    the life of the process ON PURPOSE (a declaration is what an
    already-recorded result's methods paragraph is rendered FROM, so clearing
    one would retroactively change what a finished run claims), so the answer
    has to come off the disk each time or it is a second copy of a fact that
    moves.

    A scan that FAILS answers True, and the sentence then keeps the remedy
    that assumes both add-ons are present. That is the conservative
    direction: telling a user an add-on is gone when we could not look is
    worse than telling them to remove something already removed.
    """
    from .discovery import discover_addons, extra_addon_dirs

    try:
        return any(d.manifest is not None and d.manifest.name == owner
                   for d in discover_addons(extra_dirs=extra_addon_dirs()))
    except Exception:
        logger.exception(
            "could not check whether the add-on %r is still installed while "
            "refusing an analysis key conflict", owner)
        return True


def _refuse_a_foreign_key(manifest: AddonManifest) -> None:
    """Refuse before anything is written, if a key belongs to someone else.

    THE KEY IS THE UNIT OF CREDIT. A ``StepCitation`` carries the DOIs and the
    methods sentence, and ``render_methods`` looks it up BY KEY at render time
    — so a second add-on on an already-declared key does not merely lose its
    own declaration: its run is described by the first author's sentence and
    cited with the first author's DOI, in the BibTeX, in the methods paragraph
    and in the exported ``.h5``, while its own DOI sits in the bibliography
    cited by nothing. Measured on two manifests differing in every field but
    the key — which is what a fork of the shipped example is.

    ``manifest.name`` and not the source path: re-registering from a second
    copy of one add-on's manifest is the same add-on, and the trust store keys
    consent by name for the same reason.

    Raised rather than skipped, and raised BEFORE ``register_library_entries``,
    so a refused registration leaves neither a step nor an entry behind. The
    caller turns it into a refusal that names the add-on; ``routes/addons``
    shows the same collision statically, on both rows of the listing, so a user
    meets it before a run rather than through a failed one.

    THE OWNER MAY BE GONE, and that is ordinary rather than an edge case:
    renaming a folder renames the add-on, and the declaration the old name
    made stays behind. "Remove one of the two add-ons" is then an instruction
    that cannot be carried out, because one of them no longer exists -- so
    that case gets its own sentence, which names the real state and the action
    that works. The declaration is still NOT cleared: ``render_methods`` reads
    a step's sentence at render time, so dropping one would retroactively
    change what an already-recorded result claims to have done.
    """
    for analysis in manifest.analyses:
        existing = get_step(analysis.key)
        if existing is None or existing.owner == manifest.name:
            continue
        if existing.owner and not _owner_is_installed(existing.owner):
            raise AnalysisKeyConflict(
                f"the analysis key {analysis.key!r} declared in "
                f"{manifest.source_path} is held by the add-on "
                f"{existing.owner!r}, which is no longer installed "
                f"— it was renamed or removed after it registered. "
                f"Orienta keeps a declaration for the life of the backend "
                f"process, because a result already recorded under it has its "
                f"methods sentence rendered from that declaration and must "
                f"not change afterwards. Restart the backend and "
                f"{manifest.name!r} will take the key; nothing else is "
                f"needed, and nothing has been lost.")
        raise AnalysisKeyConflict(
            f"the analysis key {analysis.key!r} declared in "
            f"{manifest.source_path} is already declared by "
            f"{_owner_description(existing)}. A key carries the citations and "
            f"the methods sentence, so registering it for {manifest.name!r} "
            f"would describe its results with another author's sentence and "
            f"cite them with another author's work. Choose a key of your own "
            f"— any key starting with 'addon.' — or remove one of the two "
            f"add-ons; Orienta will not choose.")


def register_manifest_citations(manifest: AddonManifest) -> List[str]:
    """Register one step per analysis, and its works into the library.

    Returns the library ids it contributed. Idempotent for THIS add-on: an
    analysis whose key it already declared is left as it is.

    Raises:
        AnalysisKeyConflict: if another add-on (or the core) already declared
            one of these keys. See :func:`_refuse_a_foreign_key`.
    """
    _refuse_a_foreign_key(manifest)
    entries = addon_library_entries(manifest)
    register_library_entries(entries)
    for analysis in manifest.analyses:
        # Ours already, by _refuse_a_foreign_key above: anything still
        # declared here was declared by this same add-on.
        if get_step(analysis.key) is not None:
            continue
        # The ``doi:`` prefix is not decoration: it is the LIBRARY KEY, and
        # both readers filter with ``cid in library``. A bare DOI here would
        # miss the entry registered above and delete the add-on's own work
        # from BibTeX, from the plain list and from the exported .h5 —
        # silently, because a filtered-out id leaves no trace.
        ids = tuple(analysis.citations) or (
            (f"{_DOI_PREFIX}{manifest.doi}",) if manifest.doi else ())
        register_step(StepCitation(
            key=analysis.key,
            label=analysis.label,
            citation_ids=ids,
            sentence=analysis.sentence,
            no_citation_reason=(
                None if ids else
                f"the add-on {manifest.name!r} declares no DOI and no citations"),
            owner=manifest.name,
        ))
    return sorted(entries)
